qiniu/logkit

README.md
confs/kafka_json_file.conf
mgr/runner.go
reader/kafka.go
reader/kafka_test.go
reader/reader.go
vendor/vendor.json

PDR-3726 kafka reader

---

README.md
parser/grok_parser.go
parser/grok_parser_test.go

add timezoneoffset for grok parser

---

README.md
cleaner/cleaner.go
mgr/runner.go
mgr/runner_test.go
parser/csv_parser.go
parser/grok_parser.go
parser/grok_parser_test.go
parser/inner_sql_parser.go
parser/json_parser.go
parser/qiniulog_parser.go
reader/bufreader.go
reader/bufreader_test.go
reader/elastic.go
reader/kafka.go
reader/meta.go
reader/meta_test.go
reader/mongo.go
reader/multireader_test.go
reader/mutireader.go
reader/reader.go
reader/seqfile.go
reader/singlefile.go
reader/sql.go
reader/utils.go
reader/utils_test.go
times/times_test.go
utils/utils.go

add tailx 模式，file reader支持pattern形式的路径

---

mgr/mgr.go

add cleaner log

---

README.md
logkit.go
mgr/rest.go
mgr/runner.go
sender/fault_tolerant_sender_test.go
sender/pandora_sender.go
sender/pandora_sender_test.go
vendor/vendor.json

network ratelimit and port bind

---

reader/mutireader.go
reader/singlefile.go

重构multireader

---

mgr/runner.go
mgr/runner_test.go
parser/qiniulog_parser.go
parser/qiniulog_parser_test.go
reader/singlefile.go
vendor/vendor.json

PDR-3806 将qiniulog的解析迁移至多行reader模式

---

logkit.conf
logkit.go
times/times.go
times/times_test.go

add user define timeformat layout

---

logkit.go

修复没有clean self配置会导致logkit无法关闭的问题

---

.gitignore
sender/fault_tolerant_sender_test.go
sender/pandora_sender.go
sender/pandora_sender_test.go
vendor/vendor.json

增加Pandora sender Uuid功能

---

Dockerfile
README.md
logkit.conf

add dockerfile and docker images usage

---

README.md
sender/pandora_sender.go
sender/pandora_sender_test.go
times/times_test.go

增加自动更新pandora repo的功能

---

mgr/mgr.go

change watchers use path instead of inode

---

logkit.go
metric/all/all.go
metric/registry.go
metric/system/cpu.go
metric/system/disk.go
metric/system/disk_linux.go
metric/system/disk_other.go
metric/system/kernel_linux.go
metric/system/kernel_vmstat_linux.go
metric/system/linux_sysctl_fs.go
metric/system/memory.go
metric/system/mock_PS.go
metric/system/net.go
metric/system/netstat.go
metric/system/processes.go
metric/system/ps.go
metric/system/system.go
mgr/metric_runner.go
mgr/runner.go

logkit 支持收集系统Metric信息

---

mgr/runner.go
reader/meta.go
reader/mutireader.go
reader/reader.go
reader/seqfile.go
reader/singlefile.go

add reader io limit

---

sender/pandora_sender.go
sender/pandora_sender_test.go
vendor/vendor.json

logkit totally SchemaFree

---

confs/csv.conf
confs/esreader.conf
confs/metric.conf
confs/mongo.conf
confs/mssql.conf
confs/mysql.conf
confs/raw.conf
reader/meta.go

add logkit template config

---

mgr/runner.go
vendor/vendor.json

update pandora-go-sdk vendor and fix monitor lagstat bug

---

logkit.go
sender/elasticsearch_sender.go
sender/fault_tolerant_sender.go
sender/file_sender.go
sender/influxdb_sender.go
sender/mongodb_sender.go
sender/pandora_sender.go
sender/pandora_sender_test.go
sender/sender.go
vendor/vendor.json

add Version && hotfix uint schemafree bug && senderror

---

vendor/vendor.json

fix map data lose for schemafree input

---

logkit.go
mgr/runner.go
parser/grok_parser.go
sender/pandora_sender.go
sender/pandora_sender_test.go
vendor/vendor.json

add schemafree export to logdb

---

README.md

增加了logkit配置文件帮手的链接

---

mgr/runner.go
reader/sql.go
vendor/vendor.json

更好的sql server支持

---

confs/esreader.conf
reader/elastic.go
reader/reader.go
vendor/vendor.json

支持es 5.x reader

---

sender/pandora_sender.go
sender/pandora_sender_test.go

增加forceMillisecond参数

---

mgr/runner.go
reader/elastic.go
reader/kafka.go
reader/mongo.go
reader/sql.go
sender/pandora_sender.go

增加server 数据源的等待时长

---

confs/redis.conf
mgr/mgr.go
reader/elastic.go
reader/kafka.go
reader/mongo.go
reader/reader.go
reader/redis.go
reader/sql.go

add redis reader source

---

logkit.go
reader/redis.go
vendor/vendor.json

fixes https://github.com/qiniu/logkit/issues/39

add vendor for es reader

---

parser/grok_parser.go
reader/reader.go
reader/sql.go
times/times_test.go

修复sql Server 数据存在奇葩类型时被解释为乱码的情况，增加类型schema配置功能

---

parser/csv_parser.go
parser/grok_parser.go
parser/json_parser.go
parser/kafkarest_parser.go
parser/nginx_parser.go
parser/parser.go
parser/qiniulog_parser.go
parser/rawlog_parser.go
parser/utils_test.go

change Lable's fields access to public

---

reader/multireader_test.go
reader/mutireader.go
vendor/vendor.json

自动导出到logdb的时候repo会变为小写字母

---

reader/multireader_test.go
reader/mutireader.go

去除了golang的selectCase机制，转为全部发送到mutireader的channel中

---

logkit.go
mgr/rest.go
reader/elastic.go
reader/kafka.go
reader/mongo.go
reader/multireader_test.go
reader/mutireader.go
reader/redis.go
reader/sql.go

add profile and use one time tick in reader

---

reader/elastic.go
reader/kafka.go
reader/mongo.go
reader/mutireader.go
reader/redis.go
reader/sql.go
sender/pandora_sender.go

fix sql server query

---

mgr/runner.go
queue/disk.go
queue/memory.go
queue/memory_test.go
queue/proto.go
sender/fault_tolerant_sender.go
sender/fault_tolerant_sender_test.go
sender/file_sender.go
sender/influxdb_sender.go
sender/mongodb_sender.go
sender/pandora_sender.go
sender/pandora_sender_test.go

增加memory channel，以及使用memory channel时如果channel满了会重试

---

parser/nginx_parser.go
parser/nginx_parser_test.go

增加一种手动配置Nginx 正则的方式

---

parser/csv_parser.go
parser/grok_parser.go
parser/nginx_parser.go

add space trime for parser

---

logkit.go
parser/csv_parser.go
parser/csv_parser_test.go
reader/bufreader.go
reader/bufreader_test.go
utils/utils.go

fix convert encoding && add timeoffset for csv

---

README.md

fix images

---

reader/sql.go

fix mysql export out of range panic

---

mgr/api.md
mgr/api_parser.go
mgr/api_reader.go
mgr/api_sender.go
mgr/rest.go
queue/memory.go
reader/rest_reader_models.go
sender/rest_sender_models.go
utils/models.go

add check api and fix api.md typo

---

rateio/controller.go

相关base库PR：https://github.com/qbox/base/pull/3763/files

fix rateio close bug

---

vendor/vendor.json

fix schemafree create logdb repo with json string

---

mgr/mgr.go
vendor/vendor.json

修复类型为jsonstring的情况下，空串会返回错误的问题

---

logkit.go
mgr/api.md
mgr/rest_test.go
mgr/runner.go
sender/fault_tolerant_sender.go
sender/pandora_sender.go
sender/pandora_sender_test.go
sender/sender.go
transforms/ip/ip.go
transforms/mutate/replace.go
transforms/registry.go

add more useful stats information

---

reader/bufreader.go

将byte slice直接转换成string

---

sender/fault_tolerant_sender.go

强制backup queue为disk queue

---

mgr/rest.go
mgr/runner.go
parser/rawlog_parser.go
parser/rawlog_parser_test.go
parser/rest_parser_models.go
reader/meta.go
sender/fault_tolerant_sender.go
sender/pandora_sender.go
sender/pandora_sender_test.go
transforms/ip/ip.go
transforms/ip/ip_test.go
transforms/mutate/replace.go
utils/utils.go
vendor/vendor.json

1. Marsh文件落地格式化
2. stats信息 为空缺省
3. 在非文件reader情况下meta信息不存在忽略错误
4. raw parser给用户一个是否增加时间戳的选择
5. statsinfo里面的error变为string

修复logkit前后端交互显示的bug

---

mgr/api.md
mgr/rest.go

get version api use json

---

.travis.yml

add go1.9 travis config

---

sender/rest_sender_models.go
utils/utils.go

fix logkit： repo 正则修改，remove omitempty

---

logkitweb/src/components/parserConfig.js
logkitweb/src/components/senderConfig.js
logkitweb/src/components/sourceConfig.js
logkitweb/src/createContainer.js
logkitweb/src/listContainer.js
logkitweb/src/services/logkit.js

logkitWeb web 二期增加和优化部分功能

---

mgr/runner.go
parser/rest_parser_models.go
sender/fault_tolerant_sender.go

change default parser && change send

---

sender/pandora_sender.go
sender/pandora_sender_test.go
sender/rest_sender_models.go
vendor/vendor.json

增加强制类型转换的开关，提供强制类型转换功能，解决弱类型问题

---

transforms/mutate/discard.go
transforms/mutate/discard_test.go
transforms/mutate/replace_test.go

增加discard Transformer，用于去除某个字段

---

mgr/api.md
transforms/mutate/discard.go

transformer API doc

---

mgr/api.md
mgr/api_transformer.go
mgr/api_transformer_test.go
mgr/mgr.go
mgr/rest.go
mgr/runner.go
mgr/runner_test.go
sender/pandora_sender.go
sender/sender.go
transforms/all/all.go
transforms/date/date.go
transforms/date/date_test.go
transforms/ip/ip.go
transforms/mutate/discard.go
transforms/mutate/replace.go
transforms/registry.go
utils/models.go
utils/utils.go
utils/utils_darwin.go
utils/utils_freebsd.go
utils/utils_linux.go
utils/utils_windows.go
vendor/vendor.json

增加Tranformer API && 增加时间类型的Transformer && 增加user_agent

---

mgr/api.md
mgr/rest.go
mgr/runner.go

fix logkit web runner name is empty and keep transform type

---

mgr/mgr.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
parser/csv_parser.go
parser/json_parser.go
vendor/vendor.json

1. logkit数据第一次发送前没有meta文件不再报错
2. logkit 加上runner创建时间，并在页面显示
3. logkit schemafree 创建repo失败会显示报错
4.  logkit对于解析失败的数据，展示部分原始数据方便排查错误原因

修复一系列用户体验的小问题

---

parser/rest_parser_models.go

fix qiniu parser sample log

---

README.md
reader/mongo.go
reader/sql.go

mongo reader 和 sql reader增加了一种loop模式，可以循环调用

---

logkit.go

fix clean self log

---

reader/kafka.go

修复kafka reader close方法没有调用consumer close引发consumer资源没有释放的BUG

---

sender/pandora_sender.go
sender/rest_sender_models.go
vendor/vendor.json

add auto create to kodo

---

reader/mongo.go
reader/reader.go
reader/sql.go
reader/utils.go
reader/utils_test.go

add loop time duration

---

logkit.go

版本号由 v1.3.3 升级为 v1.3.4

---

reader/rest_reader_models.go

在 logkit 配置前端页面上添加 kafka zookeeper timeout 的表单项

---

sender/fault_tolerant_sender.go
vendor/vendor.json

升级 pandora-go-sdk/base 依赖到最新版本，修复并发问题

---

mgr/mgr.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
reader/meta.go
reader/meta_test.go
reader/reader.go
sender/fault_tolerant_sender.go
sender/pandora_sender.go
sender/sender.go

将 logkit 运行状态记录到 meta 文件中，以便重启 logkit 后恢复

---

README.md
ROADMAP.md

add logkit roadmap

---

mgr/rest_test.go
mgr/runner.go
mgr/runner_test.go
reader/bufreader_test.go
reader/mutireader.go
reader/reader.go
reader/singlefile.go
reader/singlefile_test.go

修复采集单文件日志，但是文件不存在时，web端添加runner不报错的问题

---

mgr/mgr.go
mgr/mgr_test.go
mgr/runner.go

解决 RunnerStatus 并发写的问题

---

logkitweb/src/listContainer.js
mgr/metric_runner.go
mgr/rest_test.go
mgr/runner.go
reader/meta.go
sender/fault_tolerant_sender.go
sender/fault_tolerant_sender_test.go
sender/rest_sender_models.go
sender/sender.go

指定默认的 ft_sender 日志记录路径，并默认开启 ft

---

logkit.go
mgr/api.md
mgr/cluster.go
mgr/cluster_design.md
mgr/cluster_test.go
mgr/mgr.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
parser/grok_parser.go
parser/grok_parser_test.go
reader/kafka.go
reader/kafka_test.go
utils/utils.go
utils/utils_test.go
vendor/vendor.json

 logkit 集群版本框架

---

mgr/cluster.go
mgr/cluster_design.md
mgr/cluster_test.go
mgr/rest.go

为 master 添加可以给 slave 添加/删除/修改 runner 的接口

---

cleaner/cleaner_test.go
mgr/rest_test.go

尝试修复 cleaner test 概率性失败的问题，修正了两个端口冲突的问题

---

transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

添加 param transformer

---

transforms/mutate/arrayexpand.go
transforms/mutate/arrayexpand_test.go

添加 array expand transformer

---

reader/rest_reader_models.go

add logkit socket reader web option

---

logkitweb/src/container/listContainer.js
mgr/metric_runner.go
mgr/metric_runner_test.go

为metrics信息添加了时间戳，为runner开启/关闭添加二次确定

---

mgr/cluster.go
mgr/cluster_design.md
mgr/cluster_test.go

通过 master 批量管理 slaves，当满足条件的 slaves 不存在时返回 404

---

transforms/mutate/arrayexpand.go
transforms/mutate/arrayexpand_test.go
transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

更改 urlparam/arrayexpand transformer，有重复 key 时尝试更改 key 5 次, 5次后丢弃

---

sender/pandora_sender.go
sender/pandora_sender_test.go
sender/rest_sender_models.go
sender/sender.go

使用 pandora sender 时，自动添加发送时间

---

sender/pandora_sender.go
sender/pandora_sender_test.go
sender/rest_sender_models.go
utils/utils.go

pandora sender 添加是否发送机器信息(hostname/ip/core/kernel/platform)的选项

---

mgr/cluster_design.md

更新 cluster design 文件，添加 cluster 配置说明

---

logkitweb/package.json
logkitweb/src/components/metricConfig.js
logkitweb/src/components/metricKeys.js
logkitweb/src/components/metricUsages.js
logkitweb/src/components/parserConfig.js
logkitweb/src/components/renderConfig.js
logkitweb/src/components/senderConfig.js
logkitweb/src/components/sourceConfig.js
logkitweb/src/components/transformer.js
logkitweb/src/container/createLogContainer.js
logkitweb/src/container/createMetricContainer.js
logkitweb/src/container/listContainer.js
logkitweb/src/container/machine/machineTable.js
logkitweb/src/container/runner/constant.js
logkitweb/src/container/runner/runnerTable.js
logkitweb/src/container/tag/constant.js
logkitweb/src/container/tag/tagTable.js
logkitweb/src/index.css
logkitweb/src/index.js
logkitweb/src/services/logkit.js
logkitweb/src/store/config.js
logkitweb/src/utils/request.js
logkitweb/yarn.lock

增加集群版的logkitWeb的支持

---

mgr/api.md
mgr/api_metric.go
mgr/api_metric_test.go
mgr/api_parser.go
mgr/api_parser_test.go
mgr/api_reader.go
mgr/api_reader_test.go
mgr/api_sender.go
mgr/api_sender_test.go
mgr/api_transformer.go
mgr/api_transformer_test.go
mgr/cluster.go
mgr/cluster_design.md
mgr/cluster_test.go
mgr/metric_runner.go
mgr/mgr.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
utils/code.go
utils/utils.go
utils/utils_test.go

统一 logkit 请求返回格式，增加返回错误码

---

mgr/cluster.go
mgr/runner.go
mgr/runner_test.go
reader/multireader_test.go
reader/mutireader.go
reader/rest_reader_models.go
reader/seqfile.go
reader/singlefile.go
sender/pandora_sender.go
transforms/all/all.go
transforms/mutate/README.md
transforms/service/README.md
transforms/service/k8stag.go
transforms/service/k8stag_test.go
utils/utils_freebsd.go
utils/utils_linux.go
utils/utils_windows.go

修复DataSource 只加一行的bug && 使用origin file path 而不是 real file path 作为DataSource && 增加k8stag的Transformer

---

deploy/logkit_on_k8s.yaml
logkit.go

upgrade logkit on k8s yaml

---

logkitweb/src/components/senderConfig.js
logkitweb/src/container/createLogContainer.js
logkitweb/src/container/createMetricContainer.js
logkitweb/src/container/machine/machineTable.js

根据 runner 类型，前端自动开启/关闭 logdb/tsdb

---

mgr/rest.go

解决跨平台文件路径兼容性问题

---

Dockerfile

docker file version

---

mgr/cluster.go
mgr/cluster_test.go
mgr/rest.go
sender/pandora_sender.go
sender/rest_sender_models.go
vendor/github.com/qiniu/pandora-go-sdk/base/const.go
vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/api.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/error.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/interface.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/models.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/interface.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

自动导出到kodo增加可选项 && 增加agent的ip和tag配置能力

---

README.md
ROADMAP.md
metric/rest_metrics_models.go
metric/system/cpu.go
metric/system/disk.go
metric/system/net.go
parser/rest_parser_models.go
reader/rest_reader_models.go
sender/rest_sender_models.go
transforms/date/date.go
transforms/registry.go
utils/models.go

fix date transform 前端bug && add nightly build

---

logkitweb/src/components/transformer.js

修改transformer

---

logkitweb/src/container/listContainer.js
logkitweb/src/container/tag/tagTable.js
logkitweb/src/services/logkit.js
mgr/api.md
mgr/cluster.go
mgr/cluster_design.md
mgr/cluster_test.go
mgr/rest.go
mgr/rest_test.go
utils/code.go

增加 API, 前端支持批量修改 runner

---

logkit.conf
logkit.go
logkit_test.go
utils/utils.go
utils/utils_test.go

add logkit config for log

---

.gitignore
logkit.conf
logkit.go
utils/utils.go

add flag for logkit

---

parser/csv_parser.go
parser/csv_parser_test.go
parser/parser.go
parser/rest_parser_models.go

为 csv parser 添加是否自动将字段名称中的'-'更改为'_'的选项

---

mgr/rest.go

当 master 的 master url 没有 http 前缀时也自动添加上

---

sender/pandora_sender.go
sender/pandora_sender_test.go

修复了当时间精度大于微秒时，时间扰动功能导致时间戳异常的bug

---

logkitweb/src/components/parserConfig.js

parser 修改sample数据类型生效

---

logkitweb/src/components/renderConfig.js
logkitweb/src/container/createLogContainer.js
logkitweb/src/container/createMetricContainer.js
logkitweb/src/container/listContainer.js
logkitweb/src/container/machine/machineTable.js
logkitweb/src/container/runner/runnerTable.js
logkitweb/src/container/tag/constant.js
logkitweb/src/container/tag/tagTable.js

修改前端文案&&修复前端将 number 解析成 string 的 bug

---

mgr/api_parser.go
mgr/runner.go
parser/csv_parser.go
parser/csv_parser_test.go
parser/grok_parser.go
parser/grok_parser_test.go
parser/json_parser.go
parser/qiniulog_parser.go
parser/syslog_parser.go
parser/utils.go
utils/utils.go

前端样例数据测试 parser 出错时，给出详细错误信息&&修复了前端无法测试 syslog parser 的 bug

---

vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/utils.go
vendor/vendor.json

升级 pandora-go-sdk，修复 logdb 导出问题

---

logkitweb/src/components/parserConfig.js
logkitweb/src/container/listContainer.js
parser/parser.go
reader/autofile.go
reader/meta.go
reader/rest_reader_models.go
reader/seqfile.go

fix some experience issue

---

mgr/runner.go

- concurrent map read and write

fix concurrent map read and write

---

mgr/mgr.go
mgr/mgr_test.go

修复 cleanQueue gorouting 问题

---

mgr/api_sender.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
mgr/runner_test.go
sender/rest_sender_models.go
sender/sender_router.go
sender/sender_router_test.go

添加根据字段的值决定使用哪个sender发送的功能

---

script/README.md
script/createLogkitService.bat
script/logkit.sh

在linux和windows给logkit创建系统服务

---

Dockerfile
logkit.go
parser/parser.go
sender/pandora_sender.go

fix jsonstring assert

---

parser/syslog_parser_test.go
vendor/github.com/qiniu/pandora-go-sdk/base/const.go
vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/interface.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/vendor.json

update logkit fix pandora-go-sdk schema

---

reader/sql.go

fix sql reader byte without base64

---

logkit_test.go
mgr/api_metric_test.go
mgr/api_parser_test.go
mgr/api_reader_test.go
mgr/api_sender_test.go
mgr/api_transformer_test.go
mgr/cluster_test.go
mgr/metric_runner.go
mgr/metric_runner_test.go
mgr/mgr.go
mgr/mgr_test.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
reader/multireader_test.go
sender/fault_tolerant_sender.go

整理了 rest test，统一起一个服务进行测试

---

cli/upgrade.go
cli/upgrade_test.go
logkit.go
utils/utils.go

添加自动检查更新的功能

---

logkitweb/src/container/tag/tagTable.js
mgr/cluster.go
mgr/cluster_test.go
mgr/rest.go
mgr/rest_test.go

备份配置文件失败时回滚操作&&master 对 slave 的命令改为并行执行

---

sender/pandora_sender.go
utils/utils.go
utils/utils_test.go

将 null 视为非法的 jsonstring

---

reader/seqfile.go
reader/utils.go
reader/utils_test.go

用修改时间的unixnano，并且在时间相同的情况下用文件名比较

---

sender/fault_tolerant_sender.go
sender/fault_tolerant_sender_test.go
sender/pandora_sender.go
sender/pandora_sender_test.go

二分确定发送失败的数据后，将其转化为json发送

---

transforms/mutate/label.go
transforms/mutate/label_test.go
transforms/registry.go

add label transformer

---

README.md
reader/elastic.go
reader/http_reader.go
reader/http_reader_test.go
reader/kafka.go
reader/mongo.go
reader/mutireader.go
reader/reader.go
reader/redis.go
reader/rest_reader_models.go
reader/socket.go
reader/sql.go
sender/http_sender.go
sender/http_sender_test.go
sender/rest_sender_models.go
sender/sender.go
vendor/github.com/qiniu/pandora-go-sdk/base/const.go
vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/interface.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/utils.go
vendor/vendor.json

添加 http reader 和 http sender && 更新 pandora-go-sdk 依赖

---

mgr/cluster.go

修复executeToClusters 函数的 data race

---

sender/pandora_sender.go
sender/pandora_sender_test.go
sender/rest_sender_models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/vendor.json

支持打点到 dag && osInfo和metric信息使用 keyword 分词

---

reader/kafka.go
reader/reader.go
reader/rest_reader_models.go

add kafak_zookeeper_chroot option for none default kafka zk config user case

---

mgr/runner.go
mgr/runner_test.go
reader/meta.go
reader/meta_test.go
reader/multireader_test.go
reader/mutireader.go
reader/reader.go
reader/seqfile_test.go
reader/singlefile_test.go
reader/utils.go
reader/utils_test.go

add tags to data from json

---

logkitweb/src/components/renderConfig.js

修复json错误提示过于频繁

---

logkitweb/src/components/senderConfig.js
utils/utils.go
utils/utils_test.go

修复bug&&普通日志默认关掉系统信息收集

---

transforms/mutate/json.go
transforms/mutate/json_test.go

fix json transformer

---

mgr/rest.go

fix data race

---

reader/autofile.go
reader/autofile_test.go

fileauto 模式下如果判定为 dir 模式，则强制使用 tailx 模式

---

mgr/mgr.go
mgr/rest.go
mgr/runner.go

添加 add/start/stop/reset/delete runner 的接口

---

mgr/mgr.go
mgr/mgr_test.go

reader模块中各种type的日志都能获取raw_data

---

vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/vendor.json

升级 sdk, 过滤数据中的空 map

---

mgr/metric_runner.go
mgr/mgr.go
mgr/runner.go
reader/meta.go

完善runner管理失败回滚

---

mgr/runner.go
reader/multireader_test.go
reader/mutireader.go

tailx 模式支持 reset

---

mgr/mgr.go
mgr/mgr_test.go

modify get raw data

---

mgr/api_transformer.go
transforms/rest_transforms_models.go

封装获取 transform 配置项的函数

---

mgr/api_parser.go
mgr/dataflow.go
mgr/dataflow_test.go
mgr/mgr.go
mgr/mgr_test.go
parser/csv_parser_test.go

add parse data

---

mgr/dataflow_test.go
mgr/runner.go
mgr/runner_test.go
parser/csv_parser.go
parser/csv_parser_test.go
parser/grok_parser.go
parser/grok_parser_test.go
parser/json_parser.go
parser/json_parser_test.go
parser/kafkarest_parser.go
parser/kafkarest_parser_test.go
parser/nginx_parser.go
parser/nginx_parser_test.go
parser/parser.go
parser/qiniulog_parser.go
parser/qiniulog_parser_test.go
parser/rawlog_parser.go
parser/rawlog_parser_test.go
parser/rest_parser_models.go
parser/syslog_parser.go
sender/pandora_sender.go
utils/models/models.go

add pandora_stash field when parse line fail

---

mgr/api_parser.go
mgr/api_parser_test.go
mgr/api_reader.go
mgr/api_reader_test.go
mgr/api_sender.go
mgr/api_sender_test.go
mgr/api_transformer.go
mgr/api_transformer_test.go
mgr/dataflow.go
mgr/dataflow_test.go
mgr/rest.go
mgr/rest_test.go
utils/models/code.go

add send check

---

README.md
reader/reader.go
reader/rest_reader_models.go
reader/script.go
reader/script_test.go

add script reader

---

mgr/runner.go

add runner recover

---

README.md

add snmp reader

---

reader/snmp.go
vendor/github.com/qiniu/pandora-go-sdk/base/models/model.go
vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/api.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/models.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/utils.go
vendor/github.com/qiniu/pandora-go-sdk/tsdb/api.go
vendor/github.com/qiniu/pandora-go-sdk/tsdb/models.go
vendor/github.com/qiniu/pandora-go-sdk/tsdb/service.go
vendor/vendor.json

fix snmp reader panic for push data to closed channel

---

mgr/cluster_test.go
mgr/metric_runner.go
mgr/metric_runner_test.go
mgr/rest_test.go
mgr/runner.go
mgr/runner_test.go

runner 支持通过环境变量增加 tag

---

reader/snmp.go
reader/snmp_test.go

fix snmp reader panic

---

sender/pandora_sender.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/interface.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/vendor.json

pandora sender 添加 token 鉴权配置

---

reader/snmp.go
sender/pandora_sender.go

fix tokens

---

conf/map_conf.go

empty string时为默认值

---

logkit.conf
parser/rest_parser_models.go
reader/seqfile.go
sender/pandora_sender.go
sender/rest_sender_models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/vendor.json

add unescape option

---

mgr/rest.go
mgr/rest_test.go
mgr/runner.go

fix web spliter \t => \t && fix parser error not display on web

---

mgr/metric_runner.go
mgr/mgr.go
mgr/runner.go
sender/fault_tolerant_sender.go
sender/fault_tolerant_sender_test.go
sender/pandora_sender.go
sender/pandora_sender_test.go
sender/sender.go
utils/models/models.go

add refresh tokens api

---

reader/rest_reader_models.go
reader/snmp.go

snmp 默认收集频率改为 30s

---

reader/meta.go
sender/pandora_sender.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/vendor.json

update sdk,  metric 信息所有的 long 类型转换为 float 类型

---

cli/upgrade.go
cli/upgrade_test.go
mgr/dataflow_test.go
mgr/mgr.go
mgr/rest.go
mgr/rest_test.go
mgr/runner_test.go
reader/autofile_test.go
reader/bufreader_test.go
reader/meta.go
reader/meta_test.go
reader/multireader_test.go
reader/script.go
reader/script_test.go
reader/seqfile_test.go
reader/singlefile_test.go
reader/socket_test.go
reader/sql.go
reader/sql_test.go
reader/utils_test.go
sender/file_sender.go
transforms/mutate/script.go
transforms/mutate/script_test.go
transforms/registry.go
utils/models/models.go
utils/utils.go
utils/utils_test.go

add script transform

---

mgr/rest_test.go
mgr/runner.go
mgr/runner_test.go
reader/bufreader.go
reader/kafka.go
reader/kafka_test.go
reader/mutireader.go
reader/reader.go
reader/seqfile.go
reader/singlefile.go
sender/fault_tolerant_sender_test.go
utils/models/models.go
vendor/github.com/wvanbergen/kafka/consumergroup/consumer_group.go

add lag info for tailx && kafka

---

mgr/dataflow.go

add raw data limit to 2M

---

mgr/mgr.go

remove runner when dir not exist

---

transforms/mutate/convert.go
transforms/mutate/pandorakey_convert.go
transforms/mutate/pandorakey_convert_test.go
transforms/mutate/rename.go

add pandora key convert transformer

---

mgr/runner.go

fix null pointer exception

---

logkit.conf
reader/autofile.go
reader/reader.go
reader/rest_reader_models.go
reader/seqfile.go
reader/seqfile_test.go
transforms/all/all.go
transforms/aws/clocktrail.go
transforms/aws/clocktrail_test.go

add aws clocktrail transformer && add newfile new line option in dir mode reader

---

mgr/api_parser_test.go
mgr/dataflow.go
mgr/dataflow_test.go
parser/json_parser_test.go
parser/rest_parser_models.go

replace linebreak with empty string

---

sender/fault_tolerant_sender.go

sender 错误不再一直保留

---

mgr/dataflow.go
mgr/runner.go
parser/mysqllog_parser.go
parser/mysqllog_parser_test.go
parser/parser.go
parser/rest_parser_models.go
parser/syslog_parser.go
parser/syslog_parser_test.go
vendor/github.com/Preetam/mysqllog/LICENSE
vendor/github.com/Preetam/mysqllog/README.md
vendor/github.com/Preetam/mysqllog/attributes.go
vendor/github.com/Preetam/mysqllog/parser.go
vendor/vendor.json

add mysql log parser

---

metric/all/all.go
metric/curl/http.go
metric/system/cpu.go
mgr/cluster_test.go
mgr/dataflow.go
mgr/dataflow_test.go
mgr/metric_runner.go
mgr/metric_runner_test.go
mgr/rest_test.go

add http metric

---

logkitweb/src/components/parserConfig.js
logkitweb/src/components/senderConfig.js
logkitweb/src/components/sourceConfig.js
logkitweb/src/components/transformer.js

修复展开高级配置保留信息的bug

---

.gitignore
parser/rest_parser_models.go
reader/autofile.go
reader/autofile_test.go
sender/pandora_sender.go
sender/rest_sender_models.go

fixes #371
- options1...
- options2...

fix tsdb series not effect

---

README.md
deploy/logkit_on_k8s.yaml
logkit.go

add upgrade doc && v1.4.6 start

---

mgr/metric_runner.go
mgr/metric_runner_test.go
mgr/runner.go
mgr/runner_test.go

change env variable from string to map

---

mgr/mgr.go

自动创建 rest dir

---

README.md
logkit_test.go
transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

fix data type conflict

---

mgr/mgr.go
utils/utils.go

保存配置时去掉 token 信息

---

logkitweb/src/components/parserConfig.js
logkitweb/src/container/createLogContainer.js
logkitweb/src/container/createMetricContainer.js
logkitweb/src/container/runner/runnerTable.js
logkitweb/src/index.css

添加搜索，添加取消编辑，修改CSV_schema输入框样式并统计输入个数

---

mgr/mgr.go
mgr/rest.go

可以配置 mgr 不备份配置文件

---

metric/system/disk.go
metric/system/ps.go
mgr/metric_runner.go
vendor/github.com/shirou/gopsutil/cpu/cpu_windows.go
vendor/github.com/shirou/gopsutil/disk/disk_windows.go
vendor/github.com/shirou/gopsutil/mem/mem_freebsd.go
vendor/vendor.json

fix panic with more than one disk metric runner

---

logkitweb/src/components/parserConfig.js
logkitweb/src/container/createLogContainer.js

前端修复解析不支持中文的问题

---

transforms/mutate/pandorakey_convert.go
transforms/mutate/pandorakey_convert_test.go

fix pandorakey_convert

---

sender/pandora_sender.go

当 schema free 关掉时自动创建 pandora_stash 字段

---

grok_patterns/logkit-patterns
parser/grok_patterns.go

add greedydatalinefeed

---

mgr/metric_runner.go
mgr/metric_runner_test.go
mgr/runner.go
mgr/runner_test.go
parser/grok_patterns.go
reader/meta.go
reader/meta_test.go
reader/utils.go
sender/rest_sender_models.go
utils/models/models.go

add extra info as runner level

---

transforms/date/date.go
transforms/mutate/convert.go
transforms/mutate/rename.go
transforms/mutate/rename_test.go

fix transform error reminder bug

---

sender/pandora_sender.go
sender/pandora_sender_test.go
sender/rest_sender_models.go
utils/models/pandora_sender.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

add  number as float

---

sender/pandora_sender.go

sender panic fix

---

reader/bufreader.go
reader/bufreader_test.go
reader/mutireader.go

fix head pattern with 10x speed up

---

reader/clocktrail.go

Add verbose error message for looking up bucket

---

cleaner/cleaner.go
mgr/runner.go
reader/clocktrail.go
vendor/github.com/mitchellh/goamz/s3/s3.go

[PDR-5895] Use AWS4-HMAC-SHA256 as default authorization mechanism

---

cli/upgrade.go
cli/upgrade_test.go
metric/system/procstat.go
utils/os/utils_darwin.go
utils/os/utils_freebsd.go
utils/os/utils_linux.go

sleep sometime and then  retry is more reasonable than retry and then sleep sometime

sleep and then retry, this is more reasonable

---

parser/csv_parser.go
parser/rest_parser_models.go
sender/pandora_sender.go
sender/rest_sender_models.go
utils/models/pandora_sender.go
vendor/github.com/qiniu/pandora-go-sdk/base/config/config.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/github.com/qiniu/pandora-go-sdk/tsdb/service.go
vendor/vendor.json

insecure support

---

cleaner/cleaner.go
mgr/runner.go
reader/cloudtrail.go
reader/reader.go
reader/rest_reader_models.go
samples/main/main.go

fix cloudtrail

---

parser/json_parser.go
transforms/mutate/json.go

trimespace

---

reader/cloudwatch.go
transforms/aws/cloudtrail.go
transforms/aws/cloudtrail_test.go
transforms/date/date.go
transforms/date/date_test.go
transforms/mutate/convert.go
transforms/mutate/discard.go
transforms/mutate/discard_test.go
transforms/mutate/json.go
transforms/mutate/label.go
transforms/mutate/pandorakey_convert.go
transforms/mutate/rename.go
transforms/mutate/script.go
transforms/mutate/split.go
transforms/mutate/urlparam.go
transforms/mutate/xml.go
transforms/service/k8stag.go
transforms/ua/ua.go

fix transformers

---

transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

change url param contains path

---

mgr/dataflow.go
mgr/runner_test.go
parser/csv_parser.go
parser/csv_parser_test.go
parser/grok_parser.go
parser/mysqllog_parser.go
parser/nginx_parser.go
parser/nginx_parser_test.go
parser/qiniulog_parser.go
parser/qiniulog_parser_test.go
parser/rawlog_parser.go
parser/rawlog_parser_test.go
parser/syslog_parser.go

fix dataflow

---

reader/cloudwatch.go

fixcloudwath

---

reader/cloudwatch.go

fix cloudwatch

---

transforms/mutate/pandorakey_convert_test.go
utils/models/models.go

fix only number key

---

parser/grok_parser.go
parser/json_parser_test.go
parser/qiniulog_parser.go
parser/rawlog_parser.go
parser/syslog_parser.go

fix parser

---

reader/cloudtrail.go

change log level

---

logkit.go
mgr/mgr.go

fix cleaner

---

.gitignore
logkit.conf
logkit.go
mgr/cluster_test.go
mgr/metric_runner.go
mgr/mgr.go
mgr/models.go
mgr/models_test.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
mgr/runner_test.go
reader/bufreader.go
reader/cloudtrail.go
reader/reader.go
reader/rest_reader_models.go
reader/seqfile.go
reader/sql.go
reader/sql_test.go
sender/rest_sender_models.go
transforms/mutate/replace.go
transforms/mutate/trim.go
transforms/mutate/trim_test.go

add features && fix some bugs

---

vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

add more log for schemafree

---

mgr/metric_runner.go
mgr/runner.go
sender/fault_tolerant_sender.go
sender/fault_tolerant_sender_test.go
sender/pandora_sender.go
utils/models/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

fix sender error not display

---

sender/fault_tolerant_sender_test.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/vendor.json

do not update if no need

---

metric/system/linux_sysctl_fs.go
metric/system/processes.go
metric/system/system.go
metric/system/system_unix.go
metric/system/system_windows.go
vendor/github.com/shirou/gopsutil/cpu/cpu_windows.go
vendor/github.com/shirou/w32/kernel32.go

fix on windows stat

---

reader/seqfile.go
reader/seqfile_test.go
reader/singlefile.go

fix lag size show negtive

---

transforms/ua/ua.go
transforms/ua/ua_test.go

add option for useragent

---

sender/rest_sender_models.go
utils/os/signal.go

add sig quit

---

metric/system/cpu.go
metric/system/cpu_unix.go
metric/system/cpu_windows.go
metric/system/netstat.go
metric/system/procstat.go
utils/os/utils_windows.go

make cpu usage work on window

---

metric/system/netstat.go

fix netstat on windows

---

vendor/github.com/shirou/gopsutil/net/net_windows.go

add protostats on windows

---

mgr/dataflow.go
transforms/date/date.go
utils/models/utils.go
utils/models/utils_test.go

fix bugs  and adjust function

---

reader/rest_reader_models.go

add datasource for cloudtrail

---

reader/script.go

当添加从脚本收集的ScriptReader时，后台报空指针错误

fix sr.Name空指针异常

---

mgr/mgr.go
mgr/runner.go
mgr/runner_test.go
parser/csv_parser.go
parser/grok_parser.go
parser/json_parser.go
parser/mysqllog_parser.go
parser/nginx_parser.go
parser/qiniulog_parser.go
parser/rawlog_parser.go
parser/syslog_parser.go
reader/rest_reader_models.go
utils/models/models.go

修复 datasource 在数据有空行时会加不上的问题

---

logkitweb/src/container/runner/runnerTable.js

runnerTable，只有api有返回了才会继续polling

---

transforms/aws/cloudtrail.go
transforms/aws/cloudtrail_test.go

fix cloudtrailf

---

mgr/runner.go
mgr/runner_test.go

optimize datasource

---

reader/cloudtrail.go

cloudtrail add data

---

mgr/runner.go

fix larger read

---

logkitweb/src/components/renderConfig.js
logkitweb/src/container/createLogContainer.js
logkitweb/src/container/createMetricContainer.js

添加batch_size字段

---

parser/rest_parser_models.go
reader/reader.go

1. 提交runner时候pending; 2. csv提示修改

---

cleaner/cleaner.go
cleaner/cleaner_test.go
cleaner/rest_cleaner_models.go
mgr/api_cleaner.go

add get /cleaner/option api

---

reader/bufreader.go
reader/seqfile.go
reader/seqfile_test.go

Fixconfigs

---

cleaner/rest_cleaner_models.go
metric/rest_metrics_models.go
metric/system/cpu.go
metric/system/disk.go
metric/system/net.go
metric/system/procstat.go
parser/rest_parser_models.go
reader/rest_reader_models.go
sender/rest_sender_models.go
transforms/mutate/label.go
transforms/mutate/replace.go
transforms/registry.go
transforms/ua/ua.go
utils/models/models.go

add element radio

---

logkit.conf
mgr/mgr.go
reader/bufreader.go
reader/bufreader_test.go
reader/seqfile.go

fix datasource not accurate

---

reader/sql.go

check table exist

---

reader/meta.go
reader/meta_test.go
reader/seqfile.go
reader/seqfile_test.go
reader/sql.go
utils/models/utils.go

dir模式记录inode防止重复读取

---

logkitweb/src/components/parserConfig.js
logkitweb/src/components/senderConfig.js
logkitweb/src/components/sourceConfig.js
logkitweb/src/components/transformer.js
logkitweb/src/container/createLogContainer.js
logkitweb/src/container/createMetricContainer.js

1. extra_info 为undefined时，默认为false
2. 联动属性编辑时数据不存在的问题

联动属性编辑时数据不存在的问题

---

metric/system/cpu_windows.go

[bugfix]fix win cpu usage stats abnormal

---

reader/seqfile.go

reader/seqfile: add warning log for reopenForESTALE

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

GitHub templates

---

metric/registry.go
metric/rest_metrics_models.go
mgr/api_metric_test.go
mgr/metric_runner.go

[feature]support external plugins

---

.gitignore
metric/system/cpu_unix.go
metric/system/net.go

add net derivative value

---

mgr/mgr.go

修复潜在的由 fsnotify 自身引起的数据竞争
```
==================
Write at 0x00c42041a9f0 by goroutine 15:
runtime.mapdelete_faststr()
/usr/local/go/src/runtime/hashmap_fast.go:883 +0x0
github.com/qiniu/logkit/vendor/github.com/howeyc/fsnotify.(*Watcher).removeWatch()
/Users/unknwon/Applications/Go/src/github.com/qiniu/logkit/vendor/github.com/howeyc/fsnotify/fsnotify_bsd.go:257 +0x299
github.com/qiniu/logkit/vendor/github.com/howeyc/fsnotify.(*Watcher).readEvents()
/Users/unknwon/Applications/Go/src/github.com/qiniu/logkit/vendor/github.com/howeyc/fsnotify/fsnotify_bsd.go:381 +0x3dd
Previous read at 0x00c42041a9f0 by goroutine 96:
runtime.mapiternext()
/usr/local/go/src/runtime/hashmap.go:740 +0x0
github.com/qiniu/logkit/vendor/github.com/howeyc/fsnotify.(*Watcher).Close() …
```

mgr/mgr: fix potential data race in fsnotify

---

reader/sql/sql.go
reader/utils_test.go
transforms/ip/ip.go
transforms/ip/ip_test.go
utils/models/utils.go

多个IP transformer，后面一个会覆盖前面的结果
@wonderflow

rename new keys name when keys exist in ip transformer

---

reader/elastic/elastic.go
reader/kafka/kafka.go
reader/mongo/mongo.go
reader/redis/redis.go
reader/sql/sql.go

fix write on closed channel

---

transforms/ip/ip.go
transforms/ua/ua.go

为保持命名统一，[PDR-6266](https://jira.qiniu.io/browse/PDR-6266) 依赖于这个修改，然后更新相应 vendor

transforms: use constants for name of IP and ua

---

sender/rest_sender_models.go

fix kodo compress

---

logkitweb/src/components/parserConfig.js
logkitweb/src/components/senderConfig.js
logkitweb/src/components/sourceConfig.js
logkitweb/src/components/transformer.js

dvance_depend对应的属性的值为false时候，不显示该属性

---

mgr/runner.go
mgr/runner_test.go
transforms/mutate/mapreplace.go
transforms/mutate/mapreplace_test.go
utils/models/utils.go
utils/models/utils_test.go

对应的文档： https://github.com/qiniu/logkit/wiki/%5Bmapreplace%5DTransformer

add mapreplace transformer

---

transforms/mutate/convert.go
transforms/mutate/convert_test.go
transforms/mutate/mapreplace.go
transforms/mutate/mapreplace_test.go

fix mapreplace wit convert

---

reader/tailx/tailx.go

fix tailx panic

---

mgr/runner_test.go
reader/seqfile_test.go
reader/sql/sql.go
reader/sql/sql_test.go
utils/models/models.go

add lag and fix meta offset

---

reader/meta.go
reader/sql/sql.go
reader/sql/sql_test.go

@wonderflow 
1.一边读一边计算lag数量
2.读取的时候计算lag数量没有过滤掉已经读的
3.读取历史表放入一个文件中，兼容
4.stop没生效

sql bug fix

---

logkitweb/src/components/renderConfig.js
logkitweb/src/components/sourceConfig.js
logkitweb/src/components/transformer.js
logkitweb/src/container/createLogContainer.js
logkitweb/src/container/createMetricContainer.js
logkitweb/src/container/runner/runnerTable.js
logkitweb/src/index.css
logkitweb/yarn.lock

- [1 ] 另存为runner和transformer样式修改
-  @JJVvV  please review

另存为runner和transformer样式修改

---

mgr/runner.go
parser/grok/patterns.go
reader/reader.go
reader/sql/sql.go

JIRA: https://jira.qiniu.io/browse/PDR-6346
- @wonderflow

reader/sql: add DataReader to read data directly

---

queue/direct.go
queue/direct_test.go
queue/proto.go
sender/fault_tolerant.go

JIRA: https://jira.qiniu.io/browse/PDR-6346
- @wonderflow

queue: add DataQueue to directly put/read Data without en/decoding

---

parser/grok/patterns.go
sender/rest_senders_models.go

update sender model

---

reader/bufreader.go
reader/seqfile.go
reader/singlefile.go
reader/sql/sql.go
reader/tailx/tailx.go

single and seq file get lag fix bug

---

reader/rest_reader_models.go
reader/sql/sql.go
reader/sql/sql_test.go

@wonderflow 
1. database不填或者填*，默认读取所有数据库
2. 获取数据库表的时候先检查是否已经读过，再进行匹配

make mysql read all dbs in default

---

vendor/github.com/qiniu/pandora-go-sdk/logdb/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

update go sdk

---

transforms/mutate/pick.go
transforms/mutate/pick_test.go
utils/models/utils.go
utils/models/utils_test.go

logkit transform 保留指定字段

---

vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

rotate size fix 添加到vendor

---

logkit.go
mgr/rest.go
reader/elastic/elastic.go
reader/kafka/kafka.go
reader/mongo/mongo.go
reader/redis/redis.go
reader/sql/sql.go
utils/os/signal.go

定时任务会和正在执行的争取锁，抢不到加个sleep，避免死锁

---

sender/pandora/pandora.go
transforms/mutate/convert.go
transforms/mutate/convert_test.go

fix convert

---

mgr/api_reader.go
mgr/dataflow.go
reader/autofile/autofile.go
reader/cloudwatch/cloudwatch.go
reader/elastic/elastic.go
reader/http/http.go
reader/kafka/kafka.go
reader/kafka/kafka_test.go
reader/mongo/mongo.go
reader/reader.go
reader/redis/redis.go
reader/script/script.go
reader/singlefile.go
reader/snmp/snmp.go
reader/socket/socket.go
reader/sql/sql.go
reader/tailx/tailx.go
reader/tailx/tailx_test.go

修复mongo panic问题，修复try read不关闭reader的问题，并将管道型reader的错误输出

---

sender/pandora/pandora.go
sender/sender.go
utils/models/models.go

add pandora  raw sender model

---

mgr/runner.go
queuev2/kafka.go
queuev2/proto.go
sender/pandora/pandora.go

Kafkaqueue

---

metric/system/cpu.go

open cpu.collectcputime in cpu.go

open cpu.collectcputime

---

mgr/api_parser.go
mgr/api_parser_test.go
mgr/api_reader.go
mgr/api_reader_test.go
mgr/rest.go
parser/rest_parser_models.go
reader/rest_reader_models.go

add reader and parser tooltips api

---

metric/system/system.go
metric/system/system_darwin.go
metric/system/system_linux.go
metric/system/system_windows.go
mgr/runner.go

change stop() close reader first

---

mgr/dataflow.go

1. RawData 函数支持 reader.DataReader 识别
2. 调用 ReadData 方法添加超时机制

mgr/dataflow: support ReadData when get raw data

---

sender/pandora/pandora.go

Kafkaqueue pandora sender add base64 decode for string raw data

---

mgr/mgr.go

通过本地文件添加 runner 时使用文件 modtime 作为创建时间，而不是总是当前时间

mgr/mgr: use file ModTime as create time when add runner from file

---

mgr/runner.go
queuev2/kafka.go
reader/seqfile.go
reader/tailx/tailx.go
sender/pandora/pandora.go

fix not stats erorr bug

---

metric/system/system_darwin.go
metric/system/system_darwin_test.go
metric/system/system_linux.go
metric/system/system_windows.go
reader/socket/socket.go
samples/main/main.go

fix socket reader sub error panic

---

mgr/models.go

add isfromserver

---

mgr/runner.go
transforms/aws/cloudtrail.go
transforms/date/date.go
transforms/ip/ip.go
transforms/ip/ip_test.go
transforms/ip/number2ip.go
transforms/mutate/arrayexpand.go
transforms/mutate/convert.go
transforms/mutate/discard.go
transforms/mutate/json.go
transforms/mutate/label.go
transforms/mutate/mapreplace.go
transforms/mutate/pandorakey_convert.go
transforms/mutate/pick.go
transforms/mutate/rename.go
transforms/mutate/replace.go
transforms/mutate/script.go
transforms/mutate/script_test.go
transforms/mutate/split.go
transforms/mutate/trim.go
transforms/mutate/urlparam.go
transforms/mutate/xml.go
transforms/registry.go
transforms/rest_transforms_models.go
transforms/service/k8stag.go
transforms/ua/ua.go

transform error fix

---

metric/system/procstat.go
metric/system/system_darwin.go
metric/system/system_linux.go
metric/system/system_windows.go
mgr/metric_runner.go

fix system info

---

sender/rest_senders_models.go
vendor/github.com/qiniu/pandora-go-sdk/base/config/config.go
vendor/vendor.json

change api and name

---

metric/system/system_darwin.go
metric/system/system_linux.go
metric/system/system_windows.go
mgr/metric_runner.go

change metrics warn to debug

---

mgr/runner.go

use raw as default parser

---

mgr/models.go

add csv source data

---

reader/rest_reader_models.go

change reader name

---

reader/sql/sql.go
reader/sql/sql_test.go

support table with history all is false

---

README.md

change readme to logkit-community

---

mgr/mgr.go
mgr/rest.go

mgr: able to specify createTime for AddRunner

---

mgr/dataflow.go
mgr/mgr.go
mgr/rest.go
mgr/runner.go
mgr/runner_test.go
router/sender_router.go
sender/discard/discard.go
sender/elasticsearch/elasticsearch.go
sender/fault_tolerant.go
sender/file/file.go
sender/http/http.go
sender/influxdb/influxdb.go
sender/kafka/kafka.go
sender/mock/mock.go
sender/mongodb/mongodb.go
sender/sender.go

1. 优化路由检查
2. 添加 SkipDeepCopySender 用于防止 sender 之间发生数据污染

Router and sender fix

---

.travis.yml
reader/sql/sql.go
reader/sql/sql_test.go

fix bug when sync meta data in mysql

---

sender/fault_tolerant.go
sender/fault_tolerant/fault_tolerant_test.go
sender/mock_pandora/mock_pandora.go
sender/pandora/pandora.go
sender/rest_senders_models.go
sender/sender.go
vendor/github.com/qiniu/pandora-go-sdk/base/config/config.go
vendor/github.com/qiniu/pandora-go-sdk/base/const.go
vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/interface.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

2. add TypeSchemaFreeRetry error compatiable
- options1...
- options2...

1. change kodo retention default to 0 and give option

---

mgr/dataflow.go
mgr/runner.go
reader/reader.go

1. close reader 2. raw data with mock meta

---

reader/sql/sql.go
sender/http/http.go
sender/http/http_test.go
sender/rest_senders_models.go
utils/models/models.go

add body_json for http sender

---

reader/sql/sql.go
reader/sql/sql_test.go

postgres and mssql fix

---

reader/kafka/kafka.go
reader/rest_reader_models.go

fix kafka with errors return

---

transforms/mutate/json.go
transforms/mutate/mapreplace.go
transforms/mutate/mapreplace_test.go

map replace transform可以将转换的字段赋值给新字段
@wonderflow 
@Unknwon

map replace transformer add new key

---

Dockerfile.local
reader/kafka/kafka.go

fix error block

---

mgr/dataflow.go

mgr: get raw data ReadLine change to use timeout

---

reader/kafka/kafka.go
transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

add urlparam

---

reader/meta.go
reader/sql/sql.go
reader/sql/sql_test.go

sync db and tables

---

vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/vendor.json

修复export到logdb检查时omitEmpty和omitInvalid为nil导致出错的情况

---

transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

URLParam transform 支持定义仅收集哪些 key

transforms/mutate: urlparam support select keys to add

---

reader/script/script.go

script no sunch file bug fix

---

utils/models/utils.go
utils/models/utils_test.go

fix pandora key panic

---

sender/fault_tolerant.go

fix pandora sender

---

reader/cloudtrail/cloudtrail.go

reader/cloudtrail: add interface implementation check at compile time

---

reader/dirx/dir_reader.go
reader/dirx/dirx.go
utils/utils.go

reader/dirx: path not exist as expired

---

transforms/mutate/arrayexpand.go
transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

transform urlparam 转换某一条数据出错，可以继续转换

---

reader/cloudwatch/cloudwatch.go

1. 实现 DaemonReader 接口
3. 没有功能上的变更
4. 已实测

reader/cloudwatch: improve status check and implement DaemonReader

---

reader/rest_reader_models.go
reader/snmp/snmp.go
reader/snmp/snmp_test.go

make snmptable init host configurable

---

reader/elastic/elastic.go

1. 实现 DaemonReader 接口
3. 没有功能上的变更

reader/elastic: improve status check and implement DaemonReader

---

reader/http/http.go
reader/http/http_test.go

reader/http: improve status check and implement DaemonReader

---

reader/http/http.go
reader/http/http_test.go
sender/http/http_test.go

http: improve reader and sender logging

---

reader/http/http_test.go
reader/kafka/kafka.go
reader/kafka/kafka_test.go
sender/http/http_test.go

1. 代码简单梳理，编译级别改动
2. 修复 CI 环境 HTTP 相关的测试

reader/kafka: improve status check

---

reader/snmp/snmp.go
reader/snmp/snmp_test.go

1. 实现了 DaemonReader 和 DataReader 接口

reader/snmp: improve status check and implement DaemonReader, DataReader

---

reader/mongo/mongo.go
reader/mongo/mongo_test.go

reader/mongo: improve status check and implement DaemonReader

---

reader/tailx/tailx.go
reader/tailx/tailx_test.go

reader/tailx: improve status check and implement DaemonReader

---

mgr/api_transformer.go
transforms/rest_transforms_models.go

sort transform usages

---

reader/sql/sql.go
reader/sql/sql_test.go

sql test race error fix

---

mgr/api.md
mgr/mgr.go
mgr/models.go
mgr/models_test.go
mgr/rest.go
mgr/rest_test.go
mgr/runner.go
reader/meta.go
reader/meta_test.go
transforms/mutate/script.go
utils/models/code.go
utils/models/models.go
utils/models/models_test.go

获取 read parse transform send 历史错误信息，默人历史错误条数最大为100条

获取 read parse transform send 历史错误信息，默人历史错误条数最大为100条

---

mgr/models.go
mgr/models_test.go
utils/models/models.go
utils/models/models_test.go

JIRA: https://jira.qiniu.io/browse/PDR-6941
修复错误的 ErrorQueue.IsEmpty 判断，添加相关单测

mgr: fix ErrorList.Clone panic and improve empty queue check

---

mgr/models.go
mgr/runner_test.go
transforms/date/date.go
transforms/ip/ip.go
transforms/ip/mmdb.go

show extra_info

---

reader/mongo/mongo.go

修复 duration 为非正时导致 NewTicker panic

reader/mongo: add bad duration check

---

reader/sql/sql.go
reader/sql/sql_records.go

check lag and fix mysql reader offset panic

---

mgr/dataflow.go
mgr/dataflow_test.go

JIRA: https://jira.qiniu.io/browse/PDR-6987

mgr: check DaemonReader when get raw data

---

reader/socket/socket.go

修复Socket reader slice指针引用产生的数据截断

---

reader/autofile/autofile.go
reader/autofile/autofile_test.go

修复 autofile模式下如果文件夹内文件的最后修改时间不超过tailx expire时间，读取不到数据的问题

---

transforms/ip/number2ip.go
transforms/registry.go

change stage option to advane

---

vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

update pandora go sdk vendor

---

mgr/mgr.go

mgr: add new key to trim secret

---

mgr/dataflow_test.go
mgr/mgr.go
reader/http/http_test.go
reader/tailx/tailx.go
sender/http/http_test.go

fix invalid senderconfig panic

---

mgr/metric_runner.go
mgr/runner.go
utils/models/models.go
utils/models/utils.go
utils/models/utils_test.go

@wonderflow 
@Unknwon 
1. 在所有调 stats()的地方检查
2. 在runner中取last error的地方检查

检查error大小，最大限制为1024bytes

---

mgr/metric_runner.go
mgr/runner.go
parser/grok/grok.go
parser/json/json.go
parser/nginx/nginx.go
utils/models/models.go
utils/models/utils.go
utils/models/utils_test.go

修改parse相关的打印错误信息

---

mgr/dataflow.go
reader/sql/sql.go

close on sendData

---

reader/http/http_test.go
transforms/mutate/split.go
transforms/service/k8stag.go

fix k8stag key

---

sender/influxdb/influxdb.go

influxdb host 没有 http 协议头时自动添加

---

.travis.yml
parser/nginx/nginx.go
sender/http/http_test.go

JIRA: https://jira.qiniu.io/browse/PDR-6333
1. 暴露 ResolveRegexFromConf 接口
2. 改进 ResolveRegexFromConf 原来逻辑可能导致 panic 的部分
3. CI 去除 1.9 版本
4. sender/http 测试改为并行测试，缩短至原有 25% 运行时间

parser/nginx: expose ResolveRegexFromConf

---

parser/nginx/nginx.go
parser/nginx/nginx_test.go

JIRA: https://jira.qiniu.io/browse/PDR-6333
1. 添加 FindAllRegexpsFromConf（搜索所有可能的 regexp 与 log_format_name 组合）

parser/nginx: add FindAllRegexpsFromConf

---

reader/sql/sql.go
reader/sql/sql_test.go
sender/influxdb/influxdb.go

update influxdb sender log

---

mgr/runner.go

dataReader status parser=reader

---

mgr/metric_runner.go
mgr/runner.go
parser/grok/grok.go
parser/json/json.go
parser/nginx/nginx.go
reader/rest_reader_models.go
reader/socket/socket.go
reader/socket/socket_test.go
utils/models/models.go
utils/models/utils.go
utils/models/utils_test.go

add socket reader json format

---

mgr/metric_runner.go
mgr/runner.go
sender/pandora/pandora.go
sender/sender.go
utils/models/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

pandora sender中自动创建的workflow和repo添加描述信息

---

parser/builtin/builtin.go
parser/logfmt/logfmt.go
parser/logfmt/logfmt_test.go
parser/parser.go
parser/rest_parser_models.go
vendor/github.com/go-logfmt/logfmt/LICENSE
vendor/github.com/go-logfmt/logfmt/README.md
vendor/github.com/go-logfmt/logfmt/decode.go
vendor/github.com/go-logfmt/logfmt/doc.go
vendor/github.com/go-logfmt/logfmt/encode.go
vendor/github.com/go-logfmt/logfmt/fuzz.go
vendor/github.com/go-logfmt/logfmt/jsonstring.go
vendor/vendor.json

增加logfmt parser

---

parser/qiniu/qiniu.go
parser/qiniu/qiniu_test.go

fix qiniulog with teapot

---

mgr/runner.go
mgr/runner_test.go

waiting reader before runner stop

---

conf/map_conf.go
reader/rest_reader_models.go
sender/fault_tolerant.go
sender/rest_senders_models.go
sender/sender.go

1. 增加选项：磁盘使用总大小限制和写入磁盘的单条数据大小限制 2. 调整reader顺序

---

mgr/runner.go
mgr/runner_test.go
transforms/ip/ip.go

修复ip 为本地/local 时出错

---

sender/rest_senders_models.go

es sender config change

---

sender/pandora/pandora.go

https://jira.qiniu.io/browse/PDR-7411

adjust log level

---

sender/elasticsearch/elasticsearch.go
sender/fault_tolerant.go

JIRA: https://jira.qiniu.io/browse/PDR-7409
```diff
- 修复在 `bulkService.Do` 之后没有检查可能在 `BulkResponse` 中返回的错误
+- 仅向上层返回失败部分的数据，防止正常数据也被重试发送
+- 发现另一处 bug，有部分数据发送成功，runner 列表的发送计数不会增加
```

sender/elasticsearch: catch bulk response error

---

conf/map_conf.go
conf/map_conf_test.go
logkit.conf
reader/cloudtrail/cloudtrail.go
reader/cloudwatch/cloudwatch.go
reader/elastic/elastic.go
reader/mongo/mongo.go
reader/reader.go
reader/rest_reader_models.go
reader/snmp/snmp.go
reader/sql/sql.go
reader/sql/sql_test.go
sender/elasticsearch/elasticsearch.go
sender/mongodb/mongodb.go
sender/pandora/pandora.go
sender/rest_senders_models.go
utils/models/utils.go
utils/models/utils_test.go

mongodb/mysql/mssql/postgres 数据源 和 mongodb 发送器，支持从环境变量获取数据 

---

mgr/dataflow.go
mgr/dataflow_test.go
reader/builtin/builtin.go
reader/mockreader/mockreader.go
transforms/registry.go

尝试获取数据时，对readdata()方法返回值可能为nil，需要不断重试以获取有效数据。
@Unknwon

dataflow can read data rather than nil by readdata

---

metric/registry.go
metric/telegraf/memcached/memcached.go
mgr/metric_runner.go

metric add sync meta interface

---

sender/pandora/pandora.go
vendor/github.com/qiniu/pandora-go-sdk/base/config/config.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/vendor.json

设置 default region

---

sender/http/http.go
sender/http/http_test.go
sender/rest_senders_models.go

http sender中支持原样保留数据的功能，连raw字段名也不添加。
@Unknwon

http sender add raw protocol

---

sender/mock_pandora/mock_pandora.go

mock_pandora增加对stream sender的支持

mock pandora add pandora_stream's path

---

sender/http/http.go
utils/models/models.go

修复 http sender header 的问题

---

reader/snmp/snmp.go
reader/snmp/snmp_test.go

JIRA: https://jira.qiniu.io/browse/PDR-7560
@wonderflow

snmp 必须填写 snmp_tables 或者 snmp_fileds

---

sender/fault_tolerant.go
sender/fault_tolerant/fault_tolerant_test.go

* ft_sender对超过2M的数据优先使用'/n'进行分隔，若分隔后数据仍超过2M再根据分片大小进行分隔
* 改进原有分片策略
@Unknwon

ft_sender split big data with line at first

---

sender/fault_tolerant.go
sender/fault_tolerant_test.go

fix fault_tolerant lock bug

---

mgr/models.go
utils/models/models.go

compartiable

---

reader/rest_reader_models.go
reader/snmp/snmp.go

snmp reader  高级选项中的必填项设置默认值

---

README.md

add 企业版对比说明

---

reader/script/script.go
reader/script/script_test.go

@wonderflow 
https://github.com/qiniu/logkit/pull/630/files

增加 script reader 测试

---

reader/cloudwatch/cloudwatch.go
sender/pandora/pandora.go
sender/pandora/pandora_test.go
utils/models/utils.go
utils/models/utils_test.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/vendor.json

JIRA: https://jira.qiniu.io/browse/PDR-7618
@wonderflow 
@zoo4778362

schema非法字符转换

---

mgr/mgr.go
mgr/rest.go
mgr/runner.go
utils/utils.go
utils/utils_test.go

move deepcopybyjson to utils

---

mgr/runner.go

get env tags print log

---

reader/dirx/dirx.go
reader/dirx/dirx_test.go
reader/tailx/tailx.go
reader/tailx/tailx_test.go
utils/models/utils.go
utils/models/utils_test.go

@wonderflow 
@Unknwon 
@zoo4778362

submetaExpire设置为0时，expire可以不设置为0

---

vendor/github.com/clbanning/mxj/anyxml.go
vendor/github.com/clbanning/mxj/doc.go
vendor/github.com/clbanning/mxj/exists.go
vendor/github.com/clbanning/mxj/gob.go
vendor/github.com/clbanning/mxj/keyvalues.go
vendor/github.com/clbanning/mxj/readme.md
vendor/github.com/clbanning/mxj/xml.go
vendor/vendor.json

update xml vendor

---

transforms/mutate/split.go
transforms/mutate/split_test.go

split transfomer ArraryName出错处理

---

sender/builtin/builtin.go
sender/csv/csv.go
sender/csv/csv_test.go
sender/mysql/mysql.go
sender/mysql/mysql_test.go
sender/sender.go
sender/sqlfile/sqlfile.go
sender/sqlfile/sqlfile_test.go
utils/ratelimit/ratelimit.go
utils/ratelimit/ratelimit_test.go

[PDR-7731] Add mysql/csv/sqlfile senders

---

vendor/github.com/Shopify/sarama/CHANGELOG.md
vendor/github.com/Shopify/sarama/Makefile
vendor/github.com/Shopify/sarama/README.md
vendor/github.com/Shopify/sarama/admin.go
vendor/github.com/Shopify/sarama/async_producer.go
vendor/github.com/Shopify/sarama/balance_strategy.go
vendor/github.com/Shopify/sarama/broker.go
vendor/github.com/Shopify/sarama/client.go
vendor/github.com/Shopify/sarama/config.go
vendor/github.com/Shopify/sarama/consumer.go
vendor/github.com/Shopify/sarama/consumer_group.go
vendor/github.com/Shopify/sarama/dev.yml
vendor/github.com/Shopify/sarama/fetch_response.go
vendor/github.com/Shopify/sarama/length_field.go
vendor/github.com/Shopify/sarama/message_set.go
vendor/github.com/Shopify/sarama/metadata_request.go
vendor/github.com/Shopify/sarama/metadata_response.go
vendor/github.com/Shopify/sarama/mockresponses.go
vendor/github.com/Shopify/sarama/offset_manager.go
vendor/github.com/Shopify/sarama/partitioner.go
vendor/github.com/Shopify/sarama/records.go
vendor/github.com/Shopify/sarama/sync_producer.go
vendor/github.com/Shopify/sarama/utils.go
vendor/vendor.json

update sarama to v1.19.0 （vendor 20181025）， support kafka2.0.0

---

mgr/dataflow.go
mgr/dataflow_test.go

fix raw data can not get any line  when less than 10 lines

---

reader/rest_reader_models.go
reader/socket/socket.go
vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/vendor.json

fix socket reader bug and convert time.Time to string

---

metric/system/system_darwin_test.go
sender/file/writer.go

change file writer lastWrote int64 to int32

---

reader/socket/socket.go

remove one line

---

reader/dirx/dirx.go

JIRA: https://jira.qiniu.io/browse/PDR-7906
@wonderflow 
@Unknwon

fix read dirx panic

---

metric/all/all.go
metric/telegraf/elasticsearch/elasticsearch.go
metric/telegraf/http_response/http_response.go
mgr/metric_runner.go
vendor/github.com/influxdata/telegraf/plugins/inputs/elasticsearch/elasticsearch.go
vendor/github.com/influxdata/telegraf/plugins/inputs/http_response/README.md
vendor/github.com/influxdata/telegraf/plugins/inputs/http_response/http_response.go
vendor/vendor.json

support http response metric && suport transformer in metric runner

---

mgr/runner.go

fix log output panic

---

metric/system/disk.go
mgr/mgr.go
mgr/runner.go

diskio 加入部分iostat统计字段

---

conf/map_conf.go
metric/system/procstat.go
parser/csv/csv.go
parser/grok/grok.go
parser/grok/grok_test.go
parser/grok/patterns.go
parser/json/json.go
parser/kafkarest/kafkarest.go
parser/mysql/mysql.go
parser/nginx/nginx.go
parser/parser.go
parser/qiniu/qiniu.go
parser/raw/raw.go
parser/syslog/syslog.go
parser/utils.go
parser/utils_test.go
reader/bufreader.go
reader/cloudtrail/cloudtrail.go
reader/cloudwatch/cloudwatch.go
reader/seqfile.go
reader/sql/sql.go
sender/fault_tolerant.go
sender/influxdb/influxdb.go
utils/models/models.go
utils/models/utils.go
utils/models/utils_test.go

chang tranform

---

reader/redis/redis.go

change redis variable name

---

transforms/mutate/filter.go
transforms/mutate/filter_test.go

add filter transform

---

transforms/apps/redis.go
transforms/apps/redis_test.go
transforms/apps/tode.go
transforms/apps/tode_test.go
transforms/builtin/builtin.go
transforms/mutate/case.go
transforms/mutate/case_test.go

*  add redis,tode transform,support parser the log of redis and tode
* add case transform,support transfrom upper to lower or reverse

add redis,tode,case transform

---

mgr/metric_runner.go
mgr/models.go
mgr/runner.go
mgr/runner_test.go
utils/models/models.go

change speed to int64

---

reader/tailx/tailx.go

fix tailx error

---

mgr/runner.go
sender/fault_tolerant.go

fix sender bug

---

reader/sql/sql.go
reader/sql/sql_test.go

* postgreSQL支持以主键做offset进行增量读取

fix postgres sql offset

---

metric/system/net.go

logkit 增加网卡设备，用于服务端区分虚拟网卡

---

reader/dirx/dir_reader.go
reader/dirx/dirx.go
reader/dirx/dirx_test.go
reader/meta.go
reader/tailx/tailx.go
reader/tailx/tailx_test.go

@wonderflow 
@Unknwon 
@mockerzzz

1. tailx/dirx的newest只有在读取存量数据时有效 2. dirx的dataSourceTag具体到文件（之前是文件夹）

---

parser/config/config.go
parser/logfmt/logfmt.go
parser/logfmt/logfmt_test.go

* Parser [json、logfmt]支持保留原始数据

json、logfmt parsers support keep raw data

---

transforms/mutate/case.go
transforms/mutate/substring.go
transforms/mutate/substring_test.go

* 支持字段提取转换
https://jira.qiniu.io/browse/PDR-8003
@Unknwon

add substring transform

---

reader/config/config.go
reader/config/models.go
reader/dirx/dir_reader.go
reader/dirx/dirx.go
reader/dirx/dirx_test.go
reader/reader.go
reader/seqfile.go

dir/dirx增加read same inode选项

---

metric/telegraf/http_response/http_response.go
metric/telegraf/telegraf.go
sender/config/config.go

change file sender file partition default 0

---

reader/mongo/mongo.go

*  修复mongo定时任务会导致panic的问题
fixes #840
https://jira.qiniu.io/browse/PDR-8074

fix mongo corn lead to panic

---

sender/config/config.go

https://jira.qiniu.io/browse/PDR-8071

add mysql/csv/sqlfile senders config

---

mgr/models.go
mgr/runner.go
mgr/runner_test.go
parser/config/config.go
parser/raw/raw.go
parser/raw/raw_test.go
queue/direct.go
queue/direct_test.go
queue/proto.go
reader/kafka/kafka.go
sender/config/config.go
sender/config/models.go
sender/fault_tolerant.go
sender/fault_tolerant/fault_tolerant_test.go
sender/kafka/kafka.go
sender/sender.go
vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go
vendor/vendor.json

Optimize to optimize_hx

---

parser/csv/csv.go
parser/kafkarest/kafkarest.go
parser/logfmt/logfmt.go
parser/mysql/mysql.go
parser/parser.go
parser/qiniu/qiniu.go
parser/raw/raw.go
parser/syslog/syslog.go

Kafkarest/qiniu/mysql/syslog 支持多线程解析，其他解析器预分配内存

---

sender/elasticsearch/elasticsearch.go

es time change

---

sender/elasticsearch/elasticsearch.go

esClientv6 启用 easyJson

---

mgr/runner.go
parser/csv/csv.go
parser/grok/grok.go
parser/json/json.go
parser/parser.go
transforms/date/date.go
transforms/mutate/discard.go

optimize csv/grok parser and date/discard transform

---

reader/config/config.go
reader/config/models.go
reader/kafka/kafka.go
vendor/github.com/wvanbergen/kafka/consumergroup/consumer_group.go

add maxprocessing time

---

mgr/runner_test.go
parser/config/config.go
parser/config/models.go
parser/logfmt/logfmt.go
parser/logfmt/logfmt_test.go
transforms/mutate/keyvalue.go
transforms/mutate/keyvalue_test.go
vendor/github.com/go-logfmt/logfmt/CHANGELOG.md
vendor/github.com/go-logfmt/logfmt/decode.go
vendor/github.com/go-logfmt/logfmt/encode.go
vendor/github.com/go-logfmt/logfmt/go.mod
vendor/github.com/go-logfmt/logfmt/go.sum
vendor/vendor.json

1. logfmt 解析 --> key value解析 2. 增加 key value转换器

---

mgr/runner_test.go
transforms/mutate/url.go
transforms/mutate/url_test.go

增加转换器 url decode and encode

---

mgr/runner.go
transforms/mutate/urlconvert.go
transforms/mutate/urlconvert_test.go

change url to url convert

---

parser/raw/raw.go
transforms/mutate/urlparam.go
transforms/mutate/urlparam_test.go

reset url param

---

mgr/runner.go
sender/elasticsearch/elasticsearch.go
vendor/gopkg.in/olivere/elastic.v5/bulk.go

优化 es sender && 修复 lst 时间滞后的问题

---

mgr/runner.go
mgr/runner_test.go
parser/config/config.go
parser/config/models.go
parser/logfmt/logfmt.go
parser/logfmt/logfmt_test.go
reader/cloudtrail/cloudtrail.go
transforms/mutate/keyvalue.go
transforms/mutate/keyvalue_test.go
transforms/mutate/urlconvert.go
transforms/mutate/urlconvert_test.go
vendor/github.com/go-logfmt/logfmt/CHANGELOG.md
vendor/github.com/go-logfmt/logfmt/decode.go
vendor/github.com/go-logfmt/logfmt/encode.go
vendor/github.com/go-logfmt/logfmt/go.mod
vendor/github.com/go-logfmt/logfmt/go.sum
vendor/vendor.json

Optimize hx (merge master)

---

transforms/mutate/xml.go
transforms/registry.go

xml 转换值都设置为string，避免转换为float64丢失精度

---

.gitignore
audit/audit.go
audit/audit_test.go
mgr/mgr.go
mgr/models.go
mgr/runner.go
reader/sql/datagen/datagen.go
reader/sql/sql_test.go

add audit log for logkit

---

logkit.go
logkit_test.go
transforms/mutate/arrayexpand.go
transforms/mutate/urlparam.go
transforms/mutate/xml.go

1. clean_self_dir默认值从./run变为./  2. 增加clean_self_duration参数

---

metric/builtin/builtin.go
mgr/mgr.go
sender/fault_tolerant.go

check ticker stop

---

utils/models/utils.go

merge master

---

reader/http/http.go
reader/socket/socket.go

fixbugs: http or socket runner conflict on the same port

---

transforms/mutate/xml.go
transforms/mutate/xml_test.go

增加展开字段和删除key指定的键值对

---

reader/elastic/elastic.go
sender/elasticsearch/elasticsearch.go

es reader/sender 资源释放

---

mgr/mgr.go
reader/socket/socket.go

runner config和runner status同时获取

---

reader/dirx/dir_reader.go
reader/tailx/tailx.go

修复 tailx 和 dirx 设置编码格式无效的问题

---

metric/telegraf/docker/docker.go
metric/telegraf/elasticsearch/elasticsearch.go
metric/telegraf/http_response/http_response.go
utils/os/signal.go

change decode docker/es/http_response config error to warn

---

transforms/mutate/filter.go
transforms/mutate/filter_test.go

在filter中增加mode选项

---

transforms/aws/cloudtrail.go
transforms/mutate/keyvalue.go
transforms/mutate/keyvalue_test.go

change key value transform

---

transforms/mutate/trim.go
transforms/mutate/trim_test.go

trim左边和右边的时候可以去掉不断重复的部分

---

reader/sql/mongooffset.go
reader/sql/sql.go

fix misspelling error

---

reader/config/config.go
reader/socket/socket.go
reader/socket/socket_test.go
vendor/vendor.json

socket support encoding

---

utils/models/utils.go
utils/models/utils_test.go

replace 0000 with current year in date transform

---

reader/socket/socket.go

socket panic fix

---

mgr/metric_runner.go
mgr/runner.go
parser/grok/grok.go
reader/seqfile.go
reader/socket/socket.go
sender/fault_tolerant/fault_tolerant_test.go
sender/pandora/pandora.go

add more detail log info

---

times/times.go
transforms/mutate/copy.go
transforms/mutate/copy_test.go
transforms/mutate/label.go
transforms/mutate/timestamp.go
transforms/mutate/timestamp_test.go
transforms/registry.go
utils/models/utils.go

add copy and timestamp transform

---

metric/system/cpu_windows.go
metric/system/system_windows.go
metric/system/utils/gopsutil_windows.go
metric/system/utils/pgrep.go
metric/system/utils/process.go

[PDR-8388]make cpu collection compatible with windows 2003/2008

---

reader/cloudtrail/cloudtrail.go
reader/dirx/dir_reader.go
reader/dirx/dirx.go
reader/dirx/dirx_test.go
reader/reader.go
reader/seqfile.go
reader/seqfile_test.go
reader/singlefile.go
reader/singlefile_test.go
reader/tailx/tailx.go
reader/tailx/tailx_test.go
reader/test/test.go
reader/utils_test.go
utils/models/utils_test.go
utils/utils.go
utils/utils_test.go

tailx/dirx newest模式下如果expire的文件再次写入新数据可能会将老数据一起读入

---

mgr/dataflow.go
mgr/runner.go
mgr/runner_test.go
parser/builtin/builtin.go
parser/config/config.go
parser/config/models.go
parser/linuxaudit/audit.go
parser/linuxaudit/audit_test.go
parser/parser.go
transforms/ip/ip.go
transforms/registry.go
utils/models/models.go
utils/models/utils.go
vendor/github.com/axgle/mahonia/LICENSE
vendor/github.com/axgle/mahonia/README.md
vendor/vendor.json

支持linux审计日志(/var/log/audit/)标准化，redhat机型

---

metric/system/utils/gopsutil_windows.go
reader/config/config.go
tools/converter/main.go

add charset converter

---

parser/linuxaudit/audit.go
parser/linuxaudit/audit_test.go

addr in audit convert

---

parser/linuxaudit/audit.go
parser/linuxaudit/audit_test.go

audit remove empty value

---

mgr/runner.go
mgr/runner_test.go
reader/config/config.go
reader/config/models.go
reader/meta.go

add encode tag

---

parser/config/config.go
parser/logfmt/logfmt.go
parser/logfmt/logfmt_test.go
transforms/mutate/concat.go
transforms/mutate/concat_test.go
transforms/mutate/keyvalue.go
transforms/mutate/keyvalue_test.go

add concat

---

transforms/mutate/keyvalue.go

keyvalue keep_string key

---

metric/system/netstat.go
metric/system/ps.go
metric/system/system_windows.go
metric/system/utils/gopsutil_unix.go
metric/system/utils/gopsutil_windows.go

[PDR-8545]适配gopsutil库更新

---

reader/autofile/autofile.go
reader/bufreader/bufreader.go
reader/bufreader/linecache.go
reader/bufreader/linecache_test.go
reader/dirx/dir_reader.go
reader/dirx/dirx.go
reader/dirx/dirx_test.go
reader/extract/reader.go
reader/extract/reader_test.go
reader/reader.go
reader/seqfile/seqfile.go
reader/tailx/tailx.go
reader/utils.go
reader/utils_test.go

support ignoreHidden for extract reader  && fix dead lock on dirx close

---

reader/mssql/mssql.go
reader/mysql/mysql.go
reader/postgres/postgres.go

fix sql panic

---

mgr/mgr.go

mgr add reader update

---

sender/fault_tolerant.go
sender/mongodb/mongodb.go

mongodb send fix

---

sender/config/models.go

change jjh from http to https

---

reader/dirx/dir_reader.go

error trace fix

---

reader/mysql/mysql.go
reader/mysql/mysql_test.go
reader/sql/dataconvert.go
reader/sql/utils.go

time format in mysql

---

mgr/runner.go
parser/grok/patterns.go
parser/syslog/syslog.go
reader/dirx/dirx.go
transforms/mutate/convert.go
utils/models/utils.go
utils/models/utils_test.go

support time.Time in date transformer

---

sender/config/config.go
sender/csv/csv.go
sender/csv/csv_test.go

csv fix(comma support)

---

metric/system/procstat.go

lokgit 收集mac和linux进程信息修改

---

reader/config/config.go
reader/dirx/dirx.go
reader/mysql/mongooffset.go
reader/mysql/mysql.go
reader/mysql/mysql_test.go
reader/sql/compare.go
reader/sql/datagen/cmd/main.go
reader/sql/datagen/datagen.go
reader/sql/meta.go
reader/sql/time.go

support timestamp string

---

reader/postgres/postgres.go
vendor/github.com/influxdata/telegraf/CHANGELOG.md
vendor/github.com/influxdata/telegraf/Gopkg.lock
vendor/github.com/influxdata/telegraf/Gopkg.toml
vendor/github.com/influxdata/telegraf/Makefile
vendor/github.com/influxdata/telegraf/README.md
vendor/github.com/influxdata/telegraf/appveyor.yml
vendor/github.com/influxdata/telegraf/docker-compose.yml
vendor/github.com/influxdata/telegraf/internal/internal.go
vendor/github.com/influxdata/telegraf/metric/metric.go
vendor/github.com/influxdata/telegraf/metric/series_grouper.go
vendor/github.com/influxdata/telegraf/metric/tracking.go
vendor/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go
vendor/github.com/influxdata/telegraf/plugins/inputs/http_response/README.md
vendor/github.com/influxdata/telegraf/plugins/parsers/json/README.md
vendor/github.com/influxdata/telegraf/plugins/parsers/json/parser.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/vendor.json

update pandora go sdk/telegraf

---

sender/pandora/pandora.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go
vendor/vendor.json

pandora sender add map[string][string] to jsonstring 

---

reader/sql/dataconvert.go

sql add float convert

---

.travis.yml
README.md

add coverage and goreportcard

---

reader/dirx/dirx_test.go
sender/config/config.go
sender/config/models.go
sender/pandora/pandora.go
sender/pandora/pandora_test.go

logdb retention set

---

conf/load_conf_test.go
mgr/models_test.go
mgr/runner.go
mgr/runner_test.go
reader/config/config.go
sender/config/config.go

change sql to text

---

parser/config/config.go
parser/csv/csv.go
parser/csv/csv_test.go

csv parser support one field contains splitter

---

conf/load_conf_test.go
reader/cloudtrail/cloudtrail.go
reader/meta.go
vendor/github.com/mitchellh/goamz/s3/s3.go

优化 cloudtrail reader 内存使用率过高的问题

---

self/logrunner.go

agent自身日志采集使用dir模式

---

mgr/mgr.go
self/logrunner.go
self/logrunner_test.go

通过dir模式搜集agent日志

---

reader/bufreader/bufreader.go
reader/cloudtrail/cloudtrail.go
reader/config/config.go
reader/config/models.go
reader/dirx/dir_reader.go
reader/meta.go
reader/seqfile/seqfile.go
reader/seqfile/seqfile_test.go

dir模式支持不以inode作为为文件唯一标识

---

vendor/github.com/mitchellh/goamz/aws/aws.go

cloudtrail support aws cn-northwest-1

---

conf/map_conf_test.go
mgr/metric_runner.go
mgr/runner.go
sender/builtin/builtin.go
sender/config/config.go
sender/config/models.go
sender/open_falcon/transfer.go
sender/open_falcon/transfer_test.go

支持 open-falcon sender

---

sender/config/models.go
sender/pandora/pandora.go
vendor/github.com/qiniu/pandora-go-sdk/base/const.go
vendor/github.com/qiniu/pandora-go-sdk/logdb/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/service.go
vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go
vendor/vendor.json

logkit 传递配置的ak sk

---

reader/kafka/kafka.go

Fix BUG Kafka Reader Concurrent Map Iteration and Map Write

---

sender/config/config.go
sender/open_falcon/transfer.go
sender/open_falcon/transfer_test.go
transforms/mutate/xml.go
transforms/mutate/xml_test.go
utils/models/utils.go

1. Xml 字段key重复时重命名 2. open-falcon发送时将非数值型的key value 放到tags中 3. open-falcon 中url为必填

---

reader/mssql/mssql.go

mssql bug fix

---

reader/mssql/mssql.go

mssql dead lock fix

---

reader/dirx/dir_reader.go
reader/tailx/tailx.go

check file exist

---

cleaner/cleaner.go
mgr/runner.go
reader/config/config.go
reader/config/models.go
reader/seqfile/seqfile.go

cloudtrail定制版:使用时间窗口优化文件同步逻辑；修复dir模式bug

---

parser/config/config.go
parser/syslog/syslog.go
parser/syslog/syslog_test.go
utils/parse/syslog/syslog.go
utils/parse/syslog/syslog_test.go

修复timestamp错误的bug

---

parser/nginx/nginx.go
parser/nginx/nginx_test.go
parser/nginx/test_data/nginx.conf

修复nginx解析的bug

---

reader/tailx/tailx.go

修复tailx状态切换问题

---

transforms/mutate/json.go
transforms/mutate/json_test.go

add extract function in json

---

transforms/mutate/json.go
utils/models/utils.go

修复json tranformer 并发bug

---

reader/tailx/tailx.go
reader/tailx/tailx_test.go

tailx处理日志文件inode不变，直接覆盖写的情况

---

reader/config/config.go
reader/config/models.go
reader/script/script.go
reader/script/script_test.go

scripts reader 参数分隔符可配置

---

transforms/mutate/json.go
transforms/mutate/json_test.go
transforms/mutate/keyvalue.go
transforms/mutate/xml.go
transforms/registry.go

json解析后支持删除原数据

---

reader/sql/dataconvert.go
reader/sql/utils.go

自动解析sqlserver uniqueidentifier 类型的字段，转化为string

---

reader/dirx/dirx_test.go
sender/fault_tolerant.go
sender/fault_tolerant/fault_tolerant_test.go
sender/http/http.go

修复超过2M的数据切分后发送失败

---

reader/tailx/tailx.go

tailx inode变化时，不重置元数据

---

reader/mysql/mysql.go

mysql查询支持where

---

parser/csv/csv.go
parser/csv/csv_test.go
parser/logfmt/logfmt.go
parser/logfmt/logfmt_test.go

修改logfmt parse方法，其中调用了strings包，需要go1.12支持；

keyvalue 支持 下一个key以前的值都为value

---

reader/dirx/dirx.go
vendor/github.com/bmatcuk/doublestar/LICENSE
vendor/github.com/bmatcuk/doublestar/README.md
vendor/github.com/bmatcuk/doublestar/doublestar.go
vendor/github.com/bmatcuk/doublestar/go.mod
vendor/vendor.json

使用https://github.com/bmatcuk/doublestar
支持![image](https://user-images.githubusercontent.com/35253687/73810714-528ffa00-4812-11ea-91c5-ef278b7b4861.png)
@PapaPiya @BourneD @longbai

dirx模式替换glob，路径支持 ** ? 等方式

---

cleaner/cleaner.go
mgr/mgr.go
reader/dirx/dir_reader.go

原理：判断已经读完的文件总数目和总大小是否达到设置，达到了删除最老得数据
已实测
@PapaPiya @BourneD @longbai

dirx支持cleaner

---

mgr/runner.go
parser/raw/raw.go
reader/bufreader/bufreader.go
reader/dirx/dirx.go
reader/meta.go
reader/tailx/tailx.go
reader/utils.go
self/logrunner.go

@liukai2012 
@BourneD 
1. 句柄数没有控制住，导致文件过多时，kill很慢 2. syncmeta多次，文件过多时，kill较慢

tailx stop fix

---

parser/logfmt/logfmt.go
parser/logfmt/logfmt_test.go
transforms/mutate/discard.go
transforms/mutate/rename.go
transforms/mutate/rename_test.go
transforms/mutate/replace.go
transforms/mutate/substring.go
transforms/mutate/trim.go

transform(discard/replace/rename/trim/substring) performance

---

reader/sql/dataconvert.go

fix Mysql DataConvert

---

parser/syslog/syslog.go

修复 syslog datasource 错乱的问题

---

reader/mysql/mysql.go
reader/mysql/mysqloffset.go

修复mysql增加时间后无限循环

---

mgr/dataflow.go

忽略前30秒中文件不存在错误。   
- options1...
- options2...

修复dirx预览数据报文件不存在问题

---

mgr/runner.go
reader/cloudtrail/cloudtrail.go
reader/config/config.go
reader/config/models.go

s3 reader support config endpoint

---

queue/disk.go

when only one file in backup queue, fix not retry send data

---

mgr/mgr.go

Update Sender Register

---

mgr/runner.go

修复获取收集器状态卡住的问题

---

mgr/runner.go
reader/bufreader/bufreader.go
reader/bufreader/bufreader_test.go
reader/cloudtrail/cloudtrail.go
reader/dirx/dir_reader.go
reader/dirx/dirx.go
reader/tailx/tailx.go
sender/fault_tolerant.go
utils/models/models.go

1. 单行数据过大时处理读取时超过最大长度实时丢弃 2. 阻塞式发送逻辑修改

---

mgr/runner.go

readdata记录读取时间

---

utils/parse/syslog/syslog.go

[PDR-11589][fix(parser)]修复syslog解析rfc3164换行bug

---

reader/tailx/tailx.go

[PDR-11593][feat(reader)]logkit tailx 支持同时采集多个路径模式串

---

reader/mssql/mssql.go

[PDR-11516][mssql reader]mssql采集时拼接增量字段时SQL执行异常

---

utils/parse/mutate/keyvalue.go
utils/parse/mutate/keyvalue_test.go

[PDR-11786]修复keyvalue解析bug

---

reader/seqfile/seqfile.go

[PDR-11803][fix(reader)]logkit dir模式下，采集实时数据read same inode设置为true无效

---

reader/mysql/mysql.go
reader/mysql/mysql_test.go

AND 无法识别别名
- options1...
- options2...

[PDR-11860][fix(reader)]logkit mysql采集配置了递增列后，日志报sql语句错误

---

reader/mongo/mongo.go

[PDR-11924][feat(reader)]mongo过滤条件中增加对objectId的转化

---

reader/script/script.go

如果脚本执行出错，现在的逻辑没有提示有用的错误信息，需要监控cmd.Stderr进行获取错误信息

[PDR-11921][feat(reader)]logkit script reader支持输出错误信息

---

transforms/mutate/script.go

[PDR-12016][feat(transform)]script支持执行二进制文件

---

mgr/dataflow.go
mgr/metric_runner.go
mgr/runner.go
self/logrunner.go

[PDR-12026][feat(runner)]runner级别添加recover防止单个runner panic导致agent离线

---

reader/tailx/tailx.go

Windows 2008 (R2), Windows 7的服务器在文件只追加内容而不关闭文件时，文件的大小会发生变化，但文件的修改时间不会修改。
这种情况会导致tailx的IsFileModified函数一直返回false。对于读取过的文件读完之后，之后有添加内容，也不会再次启动。
2008R2验证。在不close文件，不sync的情况下文件的大小变化了，但是文件的修改时间没变。
https://user-images.githubusercontent.com/22167182/98895723-527c0380-24e2-11eb-8a81-2a22e0557646.png

[PDR-12038][fix(reader)tailx在windows机器上会延迟采集

---

transforms/date/date_test.go
utils/models/utils.go
utils/models/utils_test.go

[PDR-11314][feat(date transformer)]date没有年份时候自动加入年份时对比当前时间

---

mgr/dataflow.go

[PDR-12014][fix(transformer)]script transformer页面上会报文件不存在错误

---

metric/curl/http.go

[PDR-12225][feat(https)]http client支持https

---

mgr/metric_runner.go
mgr/mgr.go
mgr/runner.go
mgr/runner_test.go

修复runner重置reader重复启动问题

---

transforms/ip/ip.go
transforms/registry.go
utils/models/models.go

[PDR-11957][feat(key_regex)]transform处理支持字段带'-'

---

parser/config/config.go
parser/csv/csv.go
parser/csv/csv_test.go

csv解析 增加忽略字段中引号选项 和 带引号的数据解析

---

parser/logfmt/logfmt_test.go
transforms/mutate/keyvalue_test.go
utils/parse/mutate/keyvalue.go
utils/parse/mutate/keyvalue_test.go

[PDR-12858][feat(keyvalue)]keyvalue解析支持键/值包含分隔符

---

utils/parse/mutate/keyvalue.go
utils/parse/mutate/keyvalue_test.go

[PDR-12653] [fix parser] logkit keyvalue panic导致agent退出

---

parser/syslog/syslog.go
parser/syslog/syslog_test.go

fix syslog detail

---

reader/extract/reader.go

[PDR-13131][feat(zip)]当采集包含目录压缩的zip文件时，tailx只采集非目录文件

---

mgr/runner_test.go
reader/dirx/dir_reader.go
reader/dirx/dirx_test.go
reader/tailx/tailx.go
utils/utils.go

dirx/file 模式，inode不变的情况下增加数据，采集时一行数据会被拆分为多行发送

---

reader/bufreader/bufreader.go
reader/cloudtrail/cloudtrail.go
reader/dirx/dir_reader.go
reader/dirx/dirx.go
reader/dirx/dirx_test.go
reader/meta.go
reader/seqfile/seqfile.go
reader/seqfile/seqfile_test.go

修复dir会重复读取的问题

---

reader/tailx/tailx.go
utils/models/utils.go

[PDR-13372][fix(panic)]修复获取文件真实路径报空指针异常问题

---

mgr/runner_test.go
transforms/mutate/replace.go
transforms/mutate/split.go

[PDR-13448]修复transform new字段校验问题

---

reader/cloudtrail/cloudtrail.go

[PDR-13603][bug] logkit 配置 aws cloudtrail 类型数据时预取报错

---

reader/meta.go

修复filedone文件读取顺序不对导致重复采集的问题

---

queue/disk.go

[PDR-13294][fix(disk)]修复temp文件遇到error退出时不会删除的问题

---

metric/system/net.go

采集网络接口的时候，会出现内存泄漏

---

transforms/mutate/replace.go
transforms/mutate/split.go

replace,split兼容老版本key获取

---

cleaner/cleaner.go

cleaner增加状态同步，防止写channel时导致panic

---

reader/config/config.go
reader/config/models.go
reader/elastic/elastic.go
sender/fault_tolerant/fault_tolerant_test.go
utils/models/utils.go
utils/models/utils_test.go

[PDR-15176][fix]logkit es 查询 sniff的控制

---

sender/fault_tolerant.go

logkit-pro disk queue文件损坏导致io load过高

---

mgr/dataflow_test.go
reader/singlefile/singlefile.go

logkit tailx采集rotate日志丢数据

---

reader/extract/reader.go
reader/read.go
reader/utils.go
sender/sender.go

[PDR-14800][feat]logkit-pro支持.gzip格式文件采集

---

mgr/dataflow.go
reader/config/models.go
reader/meta.go

[PDR-16096][fix]: logkit 多个关键目录无法自定义配置存储路径

---

mgr/metric_runner.go
mgr/models.go

[PDR-16341][fix(meta)]: 监控采集任务meta目录设置不生效

---

sender/config/config.go
sender/config/models.go
sender/kafka/kafka.go

[PDR-17200][feat(kafka)]: 增加kafka sender version配置
