qiniu/logkit

reader/sql.go
根据go文档https://golang.org/pkg/encoding/json/#Marshal
Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.
仿照sql.go的convert方法，添加了convertString方法，避免数据被base64编码
reader/sql.go
=> 使用mysql reader时，数据均被base64编码

reader/sql.go
mysql reader在配置sql_schema时，将字段定义为string时由于可以在mr.schemas找到字段类型，但是switch中并没有处理string，因此数据会丢失
=> 字段定义为string时,会丢失数据

queue/disk.go, queue/disk_test.go, queue/proto.go, sender/fault_tolerant_sender.go, sender/fault_tolerant_sender_test.go
=> 在磁盘队列中增加内存通道

logkit.go, mgr/api.md, mgr/mgr.go, mgr/rest.go, mgr/rest_test.go, mgr/runner.go, mgr/runner_test.go, reader/bufreader.go, reader/bufreader_test.go, reader/elastic.go, reader/elastic_test.go, reader/kafka.go, reader/kafka_test.go, reader/mongo.go, reader/mongo_test.go, reader/multireader_test.go, reader/mutireader.go, reader/reader.go, reader/redis.go, reader/redis_test.go, reader/sql.go, reader/sql_test.go, sender/fault_tolerant_sender.go, utils/utils.go
=> web优化二期的后端功能支持

.github/PULL_REQUEST_TEMPLATE, logkitweb/src/listContainer.js, reader/rest_reader_models.go, sender/pandora_sender.go, sender/pandora_sender_test.go, sender/rest_sender_models.go, utils/utils.go, utils/utils_test.go
* pandora_auto_convert_date 可选字段，默认为 true开启。会自动将用户的自动尝试转换为Pandora 的时间类型(date)，pandora的时间类型为符合RFC3339格式的字符串，若已经符合该类型，则无需开启，关闭可节省CPU开销。默认开启，会尝试将进行各种类型的格式转换，包括不同的时间格式字符串的变化，整型作为unix timestamp进行转换等等。
* ignore_invalid_field 可选字段，默认为 true开启，会进行数据格式校验，并忽略不符合格式的字段数据，默认开启，关闭可以节省CPU开销。如Pandora的类型选择了jsonstring，若字符串不是合法的json字符串，就会忽略改部分字段内容，其他字段正常上报。
=> 增加了忽略不符合格式的数据选项，增强了数据校验功能，增加了是否自动转换时间的选项，增加了DataSourceTag的页面显示

parser/grok_parser.go, parser/grok_parser_test.go
=> 添加了一个函数 trimInvalidSpace 解决由于 %{a:b:c} 字符串中的空格导致的解析异常问题

parser/grok_parser.go, parser/grok_parser_test.go
=> split 后判断返回的数组长度避免数组访问越界

confs/kafka_json_file.conf, reader/kafka.go, reader/kafka_test.go, reader/reader.go
- kafka_zookeeper_timeout参数增加，单位为秒。 表示consumer连接zk时的超时时间。kafka_zookeeper_timeout必须大于2* tickTime时才有效。 tickTime一般在conf/zoo.cfg中设置。参见[zk官方文档说明](https://zookeeper.apache.org/doc/r3.1.2/zookeeperStarted.html#sc_Download)
=> 增加对kafka reader模式下，zk的timeout配置

mgr/runner.go, sender/fault_tolerant_sender.go, sender/pandora_sender.go, sender/pandora_sender_test.go, sender/sender.go
=> 兼容之前未开启 ft 的sender配置, 修复 pandora sender 失败重发时统计信息不准确的问题

mgr/cluster.go, mgr/cluster_design.md, mgr/cluster_test.go, mgr/mgr.go, mgr/rest.go
=> 完善 logkit cluster 模块

logkitweb/src/components/metricUsages.js, logkitweb/src/container/createLogContainer.js, logkitweb/src/container/createMetricContainer.js, logkitweb/src/store/config.js, metric/rest_metrics_models.go, metric/system/linux_sysctl_fs.go, mgr/metric_runner.go
=> metric 模块 bug 修复

mgr/metric_runner.go, mgr/metric_runner_test.go, mgr/runner.go, mgr/runner_test.go, parser/csv_parser.go, parser/grok_parser.go, parser/grok_parser_test.go, parser/json_parser.go, parser/kafkarest_parser.go, parser/nginx_parser.go, parser/parser.go, parser/qiniulog_parser.go, parser/rawlog_parser.go, parser/rest_parser_models.go, parser/syslog_parser.go, parser/syslog_parser_test.go, reader/kafka.go, reader/mongo.go, reader/reader.go, reader/singlefile.go, reader/socket.go, reader/socket_test.go, reader/sql.go, vendor/vendor.json
=> add Socket reader

metric/registry.go, metric/system/cpu.go, metric/system/disk.go, metric/system/kernel_linux.go, metric/system/kernel_vmstat_linux.go, metric/system/linux_sysctl_fs.go, metric/system/memory.go, metric/system/net.go, metric/system/netstat.go, metric/system/processes.go, metric/system/system.go, mgr/metric_runner.go, mgr/runner.go, sender/fault_tolerant_sender.go
=> 修正 sender 模块状态统计，更新了 metric 模块的一些字段和选项

.travis.yml
=> CI 测试时，只用 go1.9 版本，不再使用 go1.8

metric/system/cpu.go, metric/system/disk.go, metric/system/kernel_linux.go, metric/system/kernel_vmstat_linux.go, metric/system/linux_sysctl_fs.go, metric/system/memory.go, metric/system/net.go, metric/system/netstat.go, metric/system/processes.go, metric/system/system.go, mgr/metric_runner.go, mgr/metric_runner_test.go, sender/pandora_sender.go, sender/pandora_sender_test.go, utils/utils.go, vendor/github.com/qiniu/pandora-go-sdk/base/reqerr/error.go, vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go, vendor/github.com/qiniu/pandora-go-sdk/pipeline/error.go, vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go, vendor/github.com/qiniu/pandora-go-sdk/pipeline/unified.go, vendor/vendor.json
=> 为 metric 信息定义统一的时间戳字段 timestamp, 修复了失败重发数据中重复添加 osinfo 的bug

reader/seqfile.go
=> 检测下一个log文件时,对文件修改时间做纳秒级比较,解决两个文件修改时间特别接近时,略过一些文件的问题

transforms/service/k8stag.go, transforms/service/k8stag_test.go
None
让 k8s_tag transformer 支持的功能更加合理
k8s 存储 pod 中每一个容器的日志的日志文件名格式为
<pod_name>_<namespace>_<container_name>-<container_id>.log
比如
kube-proxy-00zrx_kube-system_kube-proxy-3e1efd2142307a5f3d324455899f9009e1d6ff060016cc63e4302886f4215a3a.log
pod_name: kube-proxy-00zrx
namespace: kube-system
container_name: kube-proxy
container_id: 3e1efd2142307a5f3d324455899f9009e1d6ff060016cc63e4302886f4215a3a
这个 PR，就是为了丰富 k8s_tag transformer 的功能，使他能够提供 k8s_container_name, k8s_container_id 两个字段
- options1...
- options2...
=> Fix kubernetes transformer functions

parser/csv_parser.go, parser/csv_parser_test.go
=> 使用decode来代替unmarshal,避免将int64变为科学计数法,导致后续解析出错的问题

mgr/runner.go
=> NewMetricRuuner的时候支持从外部传入SenderRegistry

mgr/mgr.go, mgr/rest.go, sender/rest_sender_models.go, utils/models.go
=> 增加web的开关选项,给前端的配置Option中加入一个字段Secret(true/false)

sender/influxdb_sender.go, sender/rest_sender_models.go
=> influxdb sender中增加自动创建database和retention policy的逻辑

cleaner/cleaner.go, mgr/runner.go, mgr/runner_test.go
调整 `LogExportRunner.Cleaner()` 逻辑，当 `cleaner != nil` 时，返回 `enable: true` 和 `logdir`，若
`cleaner == nil`，则返回 `enable: false` 和 empty `logdir`。
=> fix cleaner

metric/curl/http.go, mgr/dataflow.go, mgr/mgr.go, reader/http_reader.go, reader/mutireader.go, transforms/mutate/script.go, utils/models/utils.go
fix some type error
@wonderflow  please review
=> fix wrong type error

reader/cloudtrail.go
=> Verbose bucker region error for cloudtrail reader

Makefile
'go install' caches intermediate .a files which could speed up compilation when unchanged.
None
None
=> Makefile: use 'go install' to replace 'go build'

transforms/ip/dat.go, transforms/ip/ip.go
Even when NewLocator returns nil and assign to t.loc, because it is an interface, the t.loc itself no longer being nil.
JIRA: https://jira.qiniu.io/browse/PDR-6339
- @wonderflow 
- @redHJ
=> transforms/ip: fix panic when transform data

reader/reader.go, reader/rest_reader_models.go, reader/sql/sql.go
=> change mysql encode set

mgr/runner.go, sender/discard/discard.go, sender/elasticsearch/elasticsearch.go, sender/fault_tolerant.go, sender/fault_tolerant/fault_tolerant_test.go, sender/file/file.go, sender/http/http.go, sender/influxdb/influxdb.go, sender/kafka/kafka.go, sender/mock/mock.go, sender/mongodb/mongodb.go, sender/sender.go
=> sender: fix SkipDeepCopySender check not working

sender/pandora/pandora.go, sender/pandora/pandora_test.go, transforms/mutate/pandorakey_convert.go, utils/models/models.go, utils/models/utils.go, utils/models/utils_test.go
pandora_sender 内置 pandora key 转换(有个pandora key transformer)
@wonderflow 
@Unknwon
=> pandora_sender inner set pandora key convert

mgr/dataflow.go, mgr/runner.go, transforms/ip/ip.go, transforms/ip/ip_test.go, transforms/ip/locator.go, transforms/registry.go, transforms/ua/ua.go
IP transformer 内部维护一个 store，确保一个文件路径只会产生一个 Locator，后续调用重复利用，并确保并发查询没有竞争
=> transforms: add LocatorStore for IP to prevent init duplicated locators

reader/cloudwatch/cloudwatch.go, utils/models/utils.go, utils/models/utils_test.go
=> 优化 pandora key convert

mgr/dataflow.go, mgr/metric_runner_test.go, parser/syslog/syslog.go, parser/syslog/syslog_test.go, reader/sql/sql_test.go, utils/models/utils.go
=> syslog 出错时没有返回错误数据，大部分出错时候pandora_stash记录的数据不准确，应该为上一条数

reader/dirx/dirx.go
=> reader/dirx: warning when duplicated Close calls

times/times.go, times/times_test.go, transforms/date/date.go, transforms/date/date_test.go, transforms/mutate/convert.go, utils/models/utils.go, utils/models/utils_test.go
当 date transformer 遇到没有时区信息的时间字符串时默认为本地时间（一般情况下，为 CST）
=> transforms/date: parse as local time when timezone info is missing

reader/script/script.go, reader/script/script_test.go
1. 实现了 DaemonReader 和 StatsReader 接口
=> reader/script: improve status check and implement DaemonReader and StatsReader

reader/cloudwatch/cloudwatch.go, reader/elastic/elastic.go, reader/mongo/mongo.go, reader/redis/redis.go, reader/script/script.go, reader/snmp/snmp.go, reader/sql/sql.go
JIRA: https://jira.qiniu.io/browse/PDR-6993
=> reader: fix close of closed channel panic in very rare cases

cleaner/cleaner.go, mgr/runner_test.go, reader/dirx/dir_reader.go, reader/dirx/dirx.go, reader/dirx/dirx_test.go, reader/meta.go, reader/meta_test.go, reader/reader.go, reader/rest_reader_models.go, reader/tailx/tailx.go, reader/tailx/tailx_test.go
JIRA: https://jira.qiniu.io/browse/PDR-7006
1. tailx 和 dirx 在每次 SyncMeta 后清理过期的 submeta 目录
2. 修复 dirx 检查过期时会扫到子目录的问题
=> reader/{tailx,dirx}: clean expired submeta after sync

sender/file/file_test.go
=> sender/file: fix time conflict in test file name

mgr/dataflow_test.go, reader/http/http.go, reader/http/http_test.go, reader/rest_reader_models.go, sender/http/http_test.go
文档：https://developer.qiniu.io/insight/manual/4771/http-reader?version=5b6a6cc393b8cf242ec5d94e
=> http reader support multiple prefix

reader/cloudtrail/cloudtrail.go
JIRA: https://jira.qiniu.io/browse/PDR-7022
```diff
1. 检查判断非法的 interval 和 concurrent 选项值
2. 优化日志打印
3. 修复 syncSingleFile 的 doneChan 消费者线程无法退出，每次 sync 就会泄露一个
4. sync 之后准确地返回哪些文件是真正完成 sync 了的，然后再写进入到 metastore 里
+5. 每当同步到一定数量的文件之后就写入到 metastore，降低丢失的概率
```
=> reader/cloudtrail: improve sync process

mgr/runner.go, mgr/runner_test.go, parser/mysql/mysql.go, parser/qiniu/qiniu.go, parser/qiniu/qiniu_test.go, parser/rest_parser_models.go
=> make qiniu log parser more flexiable

sender/pandora/pandora.go, vendor/github.com/qiniu/pandora-go-sdk/pipeline/api.go, vendor/github.com/qiniu/pandora-go-sdk/pipeline/models.go, vendor/github.com/qiniu/pandora-go-sdk/pipeline/schemafree.go, vendor/vendor.json
=> logkit update export 导出到kodo的分片策略时，设置时间和大小值

logkit.go, parser/csv/csv.go, parser/csv/csv_test.go, parser/grok/grok.go, parser/grok/grok_test.go, parser/json/json.go, parser/json/json_test.go, parser/nginx/nginx.go, parser/nginx/nginx_test.go, parser/parser.go, samples/main/main.go, utils/models/models.go, utils/utils.go
=> csv,grok,json,ngnix parser添加多线程

mgr/runner.go
=> avoid reader waiting at every runner stop

mgr/runner.go, sender/mock_pandora/mock_pandora.go, sender/pandora/pandora.go, sender/pandora/pandora_test.go
@wonderflow 
1. pandora sender发送数据成功/失败条数可能出错 
2. pandora sender有别名时，原始数据被删除，如果发送出错，下一次发送时会发送空数据
=> pandora sender发送问题修复

mgr/cluster_test.go, mgr/rest_test.go, mgr/runner.go, sender/elasticsearch/elasticsearch.go, sender/fault_tolerant.go, sender/file/file.go, sender/http/http.go, sender/influxdb/influxdb.go, sender/kafka/kafka.go, sender/mock/mock.go, sender/pandora/pandora.go, sender/pandora/pandora_test.go
1. file/kafka/elasticsearch/pandora sender 返回的 err 进行修改，若有 err，返回的err类型为 StatsError，记录出错数据的数量，成功数量，最后一次出错消息，无 err，返回 nil
2. Kafka sender 中 last err 修改为 getEventMessage 和 其他错误的拼接
3. elasticsearch中的错误数量通过get failed data获得
4. runner中 send(fault_tolerant)错误数据修复，对返回的 err 进行修改，若有 err，返回的err类型为 StatsError，记录出错数据的数量，成功数量，最后一次出错消息，无 err，返回 nil
@wonderflow
=> runner sender success/failed 数量修正

sender/fault_tolerant.go, sender/fault_tolerant_test.go, sender/kafka/kafka.go
Kafka 发送器，报错问题修复：
原因：不管是否有报错都会返回statsError结构，在handleSendError中默认返回 statsError 结构则一定有错
修复：Kafka 发送器中如果有错误（statsError.Error > 0），则返回statsError结构，否则返回 nil, handleSendError 之前增加判断 send error == nil && last error == "" 来 double check 是否真正有错
@wonderflow 
@zoo4778362 
fixes https://github.com/qiniu/logkit/issues/801
=> fix kafka send error

reader/dirx/dirx_test.go, sender/config/config.go, sender/config/models.go, sender/file/file.go, sender/file/file_test.go
基本就是pr: https://github.com/qiniu/logkit/pull/831 中的内容，
变化： 1. 将增加的两个选项放在高级配置中 2. partition <= 0 改为 partition <= 1
@wonderflow
=> 发送到文件时支持将数据划分到多个文件，并且支持写入原始数据字符串(“raw”字段的数据)

mgr/dataflow_test.go, mgr/mgr.go, reader/meta.go, reader/seqfile.go, reader/singlefile.go, reader/tailx/tailx.go, reader/tailx/tailx_test.go, utils/models/models_test.go, utils/models/utils.go
@wonderflow 
1. rateReader 不填时，默认值为-1（<=0时）不限速
2. tailx读不到数据（超过3s）或者读到文件结尾（eof），停止读取，下一个扫描周期如果修改时间在扫描间隔内，则开始读取，扫描周期内出现新文件，判断是否超过expire加入内存进行读取
3. 修复 stop/start 收集器时，没有记录到文件，导致重启logkit后收集器全部启动
=> 1. tailx修改，提升性能，2. 修复stop/start重启之后没有记录is_stopped状态

mgr/runner_test.go, reader/cloudtrail/cloudtrail.go
cloudtrail的包在读取的过程中可能会读到gzip的二进制流，直接写文件会导致乱码，需要检验下头部bytes，然后对gzip的情况解压缩
=> fix cloudtrail reader with gzipped data checked

mgr/runner.go, reader/cloudtrail/cloudtrail.go, reader/cloudtrail/cloudtrail_test.go, reader/config/models.go, reader/meta.go, utils/utils.go, utils/utils_test.go
=> logkit s3 和 cloudtrail 元数据目录生成逻辑不依赖ak/sk #713

parser/logfmt/logfmt.go, parser/logfmt/logfmt_test.go, parser/syslog/syslog_test.go, transforms/mutate/keyvalue.go, transforms/mutate/keyvalue_test.go, utils/parse/mutate/keyvalue.go, utils/parse/mutate/keyvalue_test.go
将原先的有logfmt包切分，复用为parse模块里的keyvalue切分方式
=> KeyValue转换器切分方式修改

benchmark/parse_test.go, utils/parse/mutate/keyvalue.go, utils/parse/mutate/keyvalue_test.go
重写keyvalue解析逻辑，支持值为空。
优化后
BenchmarkCSV-4               49767                  21040 ns/op    csv.Parse()
BenchmarkLogfmt-4          73146                  16546 ns/op    logfmt.Parse()
BenchmarkMutate-4          340800               1628 ns/op       mutate.ScanKeyValue()
BenchmarkGoLogfmt-4     1712026               729 ns/op        go-logfmt.ScanKeyval()
=> [PDR-11786][fix(parser)]logkit采集解析Key value时，空值出错

reader/config/config.go, reader/config/models.go, reader/script/script.go, reader/script/script_test.go
=> [PDR-12106][feat(reader)]执行脚本超时时间只有5秒，不可调整，脚本执行较慢时无法使用，任务被程序直接kill

mgr/dataflow.go, mgr/metric_runner.go, mgr/runner.go, reader/cloudwatch/cloudwatch.go, reader/dirx/dir_reader.go, reader/dirx/dirx.go, reader/elastic/elastic.go, reader/httpfetch/http_fetch.go, reader/mongo/mongo.go, reader/mssql/mssql.go, reader/mysql/mysql.go, reader/postgres/postgres.go, reader/redis/redis.go, reader/script/script.go, reader/snmp/snmp.go, reader/socket/socket.go, reader/sql/utils.go, reader/tailx/tailx.go, self/logrunner.go
panic时打印信息不够具体，打印出堆栈可以方便追踪问题代码。
方便问题排查
=> [PDR-12266][feat(panic)]增加panic堆栈信息

parser/logfmt/logfmt_test.go, parser/syslog/syslog.go, parser/syslog/syslog_test.go, reader/dirx/dirx_test.go, reader/meta.go, reader/meta_test.go, reader/mysql/mysql_test.go, reader/seqfile/seqfile.go, reader/seqfile/seqfile_test.go, reader/singlefile/singlefile.go, reader/sql/datagen/datagen.go, reader/sql/time.go, reader/tailx/tailx_test.go, sender/fault_tolerant.go, sender/fault_tolerant/fault_tolerant_test.go, transforms/date/date_test.go, transforms/mutate/keyvalue_test.go, utils/models/utils_test.go, utils/parse/syslog/syslog.go, utils/parse/syslog/syslog_test.go, vendor/github.com/influxdata/go-syslog/rfc3164/machine.go, vendor/github.com/influxdata/go-syslog/rfc3164/syslog_message.go, vendor/vendor.json
=> [PDR-12988][fix(ci)]ci修复单测问题

mgr/dataflow.go, mgr/dataflow_test.go, mgr/metric_runner_test.go, reader/config/models.go, reader/tailx/tailx.go, sender/fault_tolerant/fault_tolerant_test.go, utils/parse/mutate/keyvalue_test.go
Data Race不是每次CI跑单测的时候都会提示错误，所以有几点没有注意到
1. RawDataTimeOut是全局变量，不能直接修改，所以改成可传递参数，增加默认值，不影响使用
2. tailx sendError会有channel data race问题，通过加锁或者select来避免往closed channel发数据
=> [PDR-12988][fix(ci)]修复ci data race

parser/syslog/syslog_test.go, vendor/github.com/influxdata/go-syslog/rfc3164/machine.go, vendor/vendor.json
=> [PDR-13065][feat(syslog)]syslog rfc3164解析支持月份大小写格式

reader/cloudtrail/cloudtrail.go
=> [PDR-13603][bug] 修复 s3 接口无法对接其他平台问题

mgr/dataflow_test.go, mgr/runner_test.go, reader/bufreader/bufreader.go, reader/cloudtrail/cloudtrail.go, reader/dirx/dirx_test.go
=> file、fileauto 模式，inode不变的情况下增加数据，采集时一行数据会被拆分为多行发送

mgr/runner_test.go, reader/bufreader/bufreader.go, reader/dirx/dir_reader.go, reader/dirx/dirx_test.go, reader/extract/reader.go, reader/seqfile/seqfile.go, reader/singlefile/singlefile.go, reader/tailx/tailx.go, reader/tailx/tailx_test.go
=> 1.修复文件尾行断行问题；2.修复origin不正确问题

reader/dirx/dir_reader.go, reader/dirx/dirx.go, reader/seqfile/seqfile.go
dir采集显示待读取逻辑：
old：对目录下所有文件按修改时间排序，从最新的文件开始遍历，如果不是当前在读文件，则认为是未读文件，lag会加上该文件的大小，如果是当前文件，则加上 当前文件大小 - 当前读取位置offset，遇到当前文件后退出循环，认为后续文件都是已读文件。
该逻辑在windows下是有问题的，因为windows下文件的更新时间不是及时的，即文件内容有追加后，修改时间可能是不改变的，过一段时间或者flush后，才会变动。 
- options1...
- options2...
=> [PDR-16094][fix(lag)]: dirx/dir模式下lag显示不正确
